apiVersion: carbon.taobao.com/v1
kind: RollingSet
metadata:
  name: ack-test
  annotations:
    note: This is a test annotation
  labels:
spec:
  replicas: 2
  latestVersionRatio: 100
  strategy:
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 0%

  template:
    metadata:
      labels:
        app: ack-test
    spec:
        containers:
          - image: nginx
            imagePullPolicy: IfNotPresent
            name: ack-test-pod
            ports:
              - containerPort: 8080
                protocol: TCP
            resources:
                limits: 
                    cpu: 10m
                    memory: 128Mi
            securityContext:
              capabilities: {}
              privileged: false
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        priority: 0
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default
        serviceAccountName: default
        terminationGracePeriodSeconds: 300