apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicepublishers.carbon.taobao.com
spec:
  group: carbon.taobao.com
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  names:
    kind: ServicePublisher
    plural: servicepublishers
    singular: servicepublisher
  scope: Namespaced
