// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: Admin.proto

package hippo

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using RoutePolicy within kubernetes types, where deepcopy-gen is used.
func (in *RoutePolicy) DeepCopyInto(out *RoutePolicy) {
	p := proto.Clone(in).(*RoutePolicy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutePolicy. Required by controller-gen.
func (in *RoutePolicy) DeepCopy() *RoutePolicy {
	if in == nil {
		return nil
	}
	out := new(RoutePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RoutePolicy. Required by controller-gen.
func (in *RoutePolicy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OperateRoutePolicyRequest within kubernetes types, where deepcopy-gen is used.
func (in *OperateRoutePolicyRequest) DeepCopyInto(out *OperateRoutePolicyRequest) {
	p := proto.Clone(in).(*OperateRoutePolicyRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperateRoutePolicyRequest. Required by controller-gen.
func (in *OperateRoutePolicyRequest) DeepCopy() *OperateRoutePolicyRequest {
	if in == nil {
		return nil
	}
	out := new(OperateRoutePolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OperateRoutePolicyRequest. Required by controller-gen.
func (in *OperateRoutePolicyRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OperateRoutePolicyResponse within kubernetes types, where deepcopy-gen is used.
func (in *OperateRoutePolicyResponse) DeepCopyInto(out *OperateRoutePolicyResponse) {
	p := proto.Clone(in).(*OperateRoutePolicyResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperateRoutePolicyResponse. Required by controller-gen.
func (in *OperateRoutePolicyResponse) DeepCopy() *OperateRoutePolicyResponse {
	if in == nil {
		return nil
	}
	out := new(OperateRoutePolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OperateRoutePolicyResponse. Required by controller-gen.
func (in *OperateRoutePolicyResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RoutePolicyMapping within kubernetes types, where deepcopy-gen is used.
func (in *RoutePolicyMapping) DeepCopyInto(out *RoutePolicyMapping) {
	p := proto.Clone(in).(*RoutePolicyMapping)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutePolicyMapping. Required by controller-gen.
func (in *RoutePolicyMapping) DeepCopy() *RoutePolicyMapping {
	if in == nil {
		return nil
	}
	out := new(RoutePolicyMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RoutePolicyMapping. Required by controller-gen.
func (in *RoutePolicyMapping) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OperatePolicyMappingRequest within kubernetes types, where deepcopy-gen is used.
func (in *OperatePolicyMappingRequest) DeepCopyInto(out *OperatePolicyMappingRequest) {
	p := proto.Clone(in).(*OperatePolicyMappingRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatePolicyMappingRequest. Required by controller-gen.
func (in *OperatePolicyMappingRequest) DeepCopy() *OperatePolicyMappingRequest {
	if in == nil {
		return nil
	}
	out := new(OperatePolicyMappingRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OperatePolicyMappingRequest. Required by controller-gen.
func (in *OperatePolicyMappingRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OperatePolicyMappingResponse within kubernetes types, where deepcopy-gen is used.
func (in *OperatePolicyMappingResponse) DeepCopyInto(out *OperatePolicyMappingResponse) {
	p := proto.Clone(in).(*OperatePolicyMappingResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatePolicyMappingResponse. Required by controller-gen.
func (in *OperatePolicyMappingResponse) DeepCopy() *OperatePolicyMappingResponse {
	if in == nil {
		return nil
	}
	out := new(OperatePolicyMappingResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OperatePolicyMappingResponse. Required by controller-gen.
func (in *OperatePolicyMappingResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddClusterRequest within kubernetes types, where deepcopy-gen is used.
func (in *AddClusterRequest) DeepCopyInto(out *AddClusterRequest) {
	p := proto.Clone(in).(*AddClusterRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddClusterRequest. Required by controller-gen.
func (in *AddClusterRequest) DeepCopy() *AddClusterRequest {
	if in == nil {
		return nil
	}
	out := new(AddClusterRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddClusterRequest. Required by controller-gen.
func (in *AddClusterRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelClusterRequest within kubernetes types, where deepcopy-gen is used.
func (in *DelClusterRequest) DeepCopyInto(out *DelClusterRequest) {
	p := proto.Clone(in).(*DelClusterRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelClusterRequest. Required by controller-gen.
func (in *DelClusterRequest) DeepCopy() *DelClusterRequest {
	if in == nil {
		return nil
	}
	out := new(DelClusterRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelClusterRequest. Required by controller-gen.
func (in *DelClusterRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateClusterRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateClusterRequest) DeepCopyInto(out *UpdateClusterRequest) {
	p := proto.Clone(in).(*UpdateClusterRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateClusterRequest. Required by controller-gen.
func (in *UpdateClusterRequest) DeepCopy() *UpdateClusterRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateClusterRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateClusterRequest. Required by controller-gen.
func (in *UpdateClusterRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetClusterRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetClusterRequest) DeepCopyInto(out *GetClusterRequest) {
	p := proto.Clone(in).(*GetClusterRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetClusterRequest. Required by controller-gen.
func (in *GetClusterRequest) DeepCopy() *GetClusterRequest {
	if in == nil {
		return nil
	}
	out := new(GetClusterRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetClusterRequest. Required by controller-gen.
func (in *GetClusterRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using StartClusterRequest within kubernetes types, where deepcopy-gen is used.
func (in *StartClusterRequest) DeepCopyInto(out *StartClusterRequest) {
	p := proto.Clone(in).(*StartClusterRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartClusterRequest. Required by controller-gen.
func (in *StartClusterRequest) DeepCopy() *StartClusterRequest {
	if in == nil {
		return nil
	}
	out := new(StartClusterRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new StartClusterRequest. Required by controller-gen.
func (in *StartClusterRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using StopClusterRequest within kubernetes types, where deepcopy-gen is used.
func (in *StopClusterRequest) DeepCopyInto(out *StopClusterRequest) {
	p := proto.Clone(in).(*StopClusterRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopClusterRequest. Required by controller-gen.
func (in *StopClusterRequest) DeepCopy() *StopClusterRequest {
	if in == nil {
		return nil
	}
	out := new(StopClusterRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new StopClusterRequest. Required by controller-gen.
func (in *StopClusterRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OperateClusterRequest within kubernetes types, where deepcopy-gen is used.
func (in *OperateClusterRequest) DeepCopyInto(out *OperateClusterRequest) {
	p := proto.Clone(in).(*OperateClusterRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperateClusterRequest. Required by controller-gen.
func (in *OperateClusterRequest) DeepCopy() *OperateClusterRequest {
	if in == nil {
		return nil
	}
	out := new(OperateClusterRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OperateClusterRequest. Required by controller-gen.
func (in *OperateClusterRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppFedStat within kubernetes types, where deepcopy-gen is used.
func (in *AppFedStat) DeepCopyInto(out *AppFedStat) {
	p := proto.Clone(in).(*AppFedStat)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppFedStat. Required by controller-gen.
func (in *AppFedStat) DeepCopy() *AppFedStat {
	if in == nil {
		return nil
	}
	out := new(AppFedStat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppFedStat. Required by controller-gen.
func (in *AppFedStat) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClusterStatus within kubernetes types, where deepcopy-gen is used.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	p := proto.Clone(in).(*ClusterStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus. Required by controller-gen.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus. Required by controller-gen.
func (in *ClusterStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetClusterResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetClusterResponse) DeepCopyInto(out *GetClusterResponse) {
	p := proto.Clone(in).(*GetClusterResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetClusterResponse. Required by controller-gen.
func (in *GetClusterResponse) DeepCopy() *GetClusterResponse {
	if in == nil {
		return nil
	}
	out := new(GetClusterResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetClusterResponse. Required by controller-gen.
func (in *GetClusterResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddSlaveRequest within kubernetes types, where deepcopy-gen is used.
func (in *AddSlaveRequest) DeepCopyInto(out *AddSlaveRequest) {
	p := proto.Clone(in).(*AddSlaveRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddSlaveRequest. Required by controller-gen.
func (in *AddSlaveRequest) DeepCopy() *AddSlaveRequest {
	if in == nil {
		return nil
	}
	out := new(AddSlaveRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddSlaveRequest. Required by controller-gen.
func (in *AddSlaveRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddSlaveResponse within kubernetes types, where deepcopy-gen is used.
func (in *AddSlaveResponse) DeepCopyInto(out *AddSlaveResponse) {
	p := proto.Clone(in).(*AddSlaveResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddSlaveResponse. Required by controller-gen.
func (in *AddSlaveResponse) DeepCopy() *AddSlaveResponse {
	if in == nil {
		return nil
	}
	out := new(AddSlaveResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddSlaveResponse. Required by controller-gen.
func (in *AddSlaveResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelSlaveRequest within kubernetes types, where deepcopy-gen is used.
func (in *DelSlaveRequest) DeepCopyInto(out *DelSlaveRequest) {
	p := proto.Clone(in).(*DelSlaveRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelSlaveRequest. Required by controller-gen.
func (in *DelSlaveRequest) DeepCopy() *DelSlaveRequest {
	if in == nil {
		return nil
	}
	out := new(DelSlaveRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelSlaveRequest. Required by controller-gen.
func (in *DelSlaveRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelSlaveResponse within kubernetes types, where deepcopy-gen is used.
func (in *DelSlaveResponse) DeepCopyInto(out *DelSlaveResponse) {
	p := proto.Clone(in).(*DelSlaveResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelSlaveResponse. Required by controller-gen.
func (in *DelSlaveResponse) DeepCopy() *DelSlaveResponse {
	if in == nil {
		return nil
	}
	out := new(DelSlaveResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelSlaveResponse. Required by controller-gen.
func (in *DelSlaveResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OfflineSlaveRequest within kubernetes types, where deepcopy-gen is used.
func (in *OfflineSlaveRequest) DeepCopyInto(out *OfflineSlaveRequest) {
	p := proto.Clone(in).(*OfflineSlaveRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OfflineSlaveRequest. Required by controller-gen.
func (in *OfflineSlaveRequest) DeepCopy() *OfflineSlaveRequest {
	if in == nil {
		return nil
	}
	out := new(OfflineSlaveRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OfflineSlaveRequest. Required by controller-gen.
func (in *OfflineSlaveRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OfflineSlaveResponse within kubernetes types, where deepcopy-gen is used.
func (in *OfflineSlaveResponse) DeepCopyInto(out *OfflineSlaveResponse) {
	p := proto.Clone(in).(*OfflineSlaveResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OfflineSlaveResponse. Required by controller-gen.
func (in *OfflineSlaveResponse) DeepCopy() *OfflineSlaveResponse {
	if in == nil {
		return nil
	}
	out := new(OfflineSlaveResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OfflineSlaveResponse. Required by controller-gen.
func (in *OfflineSlaveResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OnlineSlaveRequest within kubernetes types, where deepcopy-gen is used.
func (in *OnlineSlaveRequest) DeepCopyInto(out *OnlineSlaveRequest) {
	p := proto.Clone(in).(*OnlineSlaveRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnlineSlaveRequest. Required by controller-gen.
func (in *OnlineSlaveRequest) DeepCopy() *OnlineSlaveRequest {
	if in == nil {
		return nil
	}
	out := new(OnlineSlaveRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OnlineSlaveRequest. Required by controller-gen.
func (in *OnlineSlaveRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OnlineSlaveResponse within kubernetes types, where deepcopy-gen is used.
func (in *OnlineSlaveResponse) DeepCopyInto(out *OnlineSlaveResponse) {
	p := proto.Clone(in).(*OnlineSlaveResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnlineSlaveResponse. Required by controller-gen.
func (in *OnlineSlaveResponse) DeepCopy() *OnlineSlaveResponse {
	if in == nil {
		return nil
	}
	out := new(OnlineSlaveResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OnlineSlaveResponse. Required by controller-gen.
func (in *OnlineSlaveResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using FreezeSlaveRequest within kubernetes types, where deepcopy-gen is used.
func (in *FreezeSlaveRequest) DeepCopyInto(out *FreezeSlaveRequest) {
	p := proto.Clone(in).(*FreezeSlaveRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreezeSlaveRequest. Required by controller-gen.
func (in *FreezeSlaveRequest) DeepCopy() *FreezeSlaveRequest {
	if in == nil {
		return nil
	}
	out := new(FreezeSlaveRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new FreezeSlaveRequest. Required by controller-gen.
func (in *FreezeSlaveRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using FreezeSlaveResponse within kubernetes types, where deepcopy-gen is used.
func (in *FreezeSlaveResponse) DeepCopyInto(out *FreezeSlaveResponse) {
	p := proto.Clone(in).(*FreezeSlaveResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreezeSlaveResponse. Required by controller-gen.
func (in *FreezeSlaveResponse) DeepCopy() *FreezeSlaveResponse {
	if in == nil {
		return nil
	}
	out := new(FreezeSlaveResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new FreezeSlaveResponse. Required by controller-gen.
func (in *FreezeSlaveResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddResourceRequest within kubernetes types, where deepcopy-gen is used.
func (in *AddResourceRequest) DeepCopyInto(out *AddResourceRequest) {
	p := proto.Clone(in).(*AddResourceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddResourceRequest. Required by controller-gen.
func (in *AddResourceRequest) DeepCopy() *AddResourceRequest {
	if in == nil {
		return nil
	}
	out := new(AddResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddResourceRequest. Required by controller-gen.
func (in *AddResourceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddResourceResponse within kubernetes types, where deepcopy-gen is used.
func (in *AddResourceResponse) DeepCopyInto(out *AddResourceResponse) {
	p := proto.Clone(in).(*AddResourceResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddResourceResponse. Required by controller-gen.
func (in *AddResourceResponse) DeepCopy() *AddResourceResponse {
	if in == nil {
		return nil
	}
	out := new(AddResourceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddResourceResponse. Required by controller-gen.
func (in *AddResourceResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelResourceRequest within kubernetes types, where deepcopy-gen is used.
func (in *DelResourceRequest) DeepCopyInto(out *DelResourceRequest) {
	p := proto.Clone(in).(*DelResourceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelResourceRequest. Required by controller-gen.
func (in *DelResourceRequest) DeepCopy() *DelResourceRequest {
	if in == nil {
		return nil
	}
	out := new(DelResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelResourceRequest. Required by controller-gen.
func (in *DelResourceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelResourceResponse within kubernetes types, where deepcopy-gen is used.
func (in *DelResourceResponse) DeepCopyInto(out *DelResourceResponse) {
	p := proto.Clone(in).(*DelResourceResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelResourceResponse. Required by controller-gen.
func (in *DelResourceResponse) DeepCopy() *DelResourceResponse {
	if in == nil {
		return nil
	}
	out := new(DelResourceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelResourceResponse. Required by controller-gen.
func (in *DelResourceResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateResourceRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateResourceRequest) DeepCopyInto(out *UpdateResourceRequest) {
	p := proto.Clone(in).(*UpdateResourceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourceRequest. Required by controller-gen.
func (in *UpdateResourceRequest) DeepCopy() *UpdateResourceRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourceRequest. Required by controller-gen.
func (in *UpdateResourceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateResourceResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateResourceResponse) DeepCopyInto(out *UpdateResourceResponse) {
	p := proto.Clone(in).(*UpdateResourceResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourceResponse. Required by controller-gen.
func (in *UpdateResourceResponse) DeepCopy() *UpdateResourceResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateResourceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourceResponse. Required by controller-gen.
func (in *UpdateResourceResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OfflineSlotRequest within kubernetes types, where deepcopy-gen is used.
func (in *OfflineSlotRequest) DeepCopyInto(out *OfflineSlotRequest) {
	p := proto.Clone(in).(*OfflineSlotRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OfflineSlotRequest. Required by controller-gen.
func (in *OfflineSlotRequest) DeepCopy() *OfflineSlotRequest {
	if in == nil {
		return nil
	}
	out := new(OfflineSlotRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OfflineSlotRequest. Required by controller-gen.
func (in *OfflineSlotRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OfflineSlotResponse within kubernetes types, where deepcopy-gen is used.
func (in *OfflineSlotResponse) DeepCopyInto(out *OfflineSlotResponse) {
	p := proto.Clone(in).(*OfflineSlotResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OfflineSlotResponse. Required by controller-gen.
func (in *OfflineSlotResponse) DeepCopy() *OfflineSlotResponse {
	if in == nil {
		return nil
	}
	out := new(OfflineSlotResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OfflineSlotResponse. Required by controller-gen.
func (in *OfflineSlotResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClearOfflineSlotRequest within kubernetes types, where deepcopy-gen is used.
func (in *ClearOfflineSlotRequest) DeepCopyInto(out *ClearOfflineSlotRequest) {
	p := proto.Clone(in).(*ClearOfflineSlotRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearOfflineSlotRequest. Required by controller-gen.
func (in *ClearOfflineSlotRequest) DeepCopy() *ClearOfflineSlotRequest {
	if in == nil {
		return nil
	}
	out := new(ClearOfflineSlotRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClearOfflineSlotRequest. Required by controller-gen.
func (in *ClearOfflineSlotRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClearOfflineSlotResponse within kubernetes types, where deepcopy-gen is used.
func (in *ClearOfflineSlotResponse) DeepCopyInto(out *ClearOfflineSlotResponse) {
	p := proto.Clone(in).(*ClearOfflineSlotResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearOfflineSlotResponse. Required by controller-gen.
func (in *ClearOfflineSlotResponse) DeepCopy() *ClearOfflineSlotResponse {
	if in == nil {
		return nil
	}
	out := new(ClearOfflineSlotResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClearOfflineSlotResponse. Required by controller-gen.
func (in *ClearOfflineSlotResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using OfflineSlotInfo within kubernetes types, where deepcopy-gen is used.
func (in *OfflineSlotInfo) DeepCopyInto(out *OfflineSlotInfo) {
	p := proto.Clone(in).(*OfflineSlotInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OfflineSlotInfo. Required by controller-gen.
func (in *OfflineSlotInfo) DeepCopy() *OfflineSlotInfo {
	if in == nil {
		return nil
	}
	out := new(OfflineSlotInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OfflineSlotInfo. Required by controller-gen.
func (in *OfflineSlotInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetOfflineSlotRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetOfflineSlotRequest) DeepCopyInto(out *GetOfflineSlotRequest) {
	p := proto.Clone(in).(*GetOfflineSlotRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetOfflineSlotRequest. Required by controller-gen.
func (in *GetOfflineSlotRequest) DeepCopy() *GetOfflineSlotRequest {
	if in == nil {
		return nil
	}
	out := new(GetOfflineSlotRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetOfflineSlotRequest. Required by controller-gen.
func (in *GetOfflineSlotRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetOfflineSlotResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetOfflineSlotResponse) DeepCopyInto(out *GetOfflineSlotResponse) {
	p := proto.Clone(in).(*GetOfflineSlotResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetOfflineSlotResponse. Required by controller-gen.
func (in *GetOfflineSlotResponse) DeepCopy() *GetOfflineSlotResponse {
	if in == nil {
		return nil
	}
	out := new(GetOfflineSlotResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetOfflineSlotResponse. Required by controller-gen.
func (in *GetOfflineSlotResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateAllReservedResourceRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateAllReservedResourceRequest) DeepCopyInto(out *UpdateAllReservedResourceRequest) {
	p := proto.Clone(in).(*UpdateAllReservedResourceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateAllReservedResourceRequest. Required by controller-gen.
func (in *UpdateAllReservedResourceRequest) DeepCopy() *UpdateAllReservedResourceRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateAllReservedResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateAllReservedResourceRequest. Required by controller-gen.
func (in *UpdateAllReservedResourceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateAllReservedResourceResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateAllReservedResourceResponse) DeepCopyInto(out *UpdateAllReservedResourceResponse) {
	p := proto.Clone(in).(*UpdateAllReservedResourceResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateAllReservedResourceResponse. Required by controller-gen.
func (in *UpdateAllReservedResourceResponse) DeepCopy() *UpdateAllReservedResourceResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateAllReservedResourceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateAllReservedResourceResponse. Required by controller-gen.
func (in *UpdateAllReservedResourceResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateDefaultSlaveRuntimeConfigRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateDefaultSlaveRuntimeConfigRequest) DeepCopyInto(out *UpdateDefaultSlaveRuntimeConfigRequest) {
	p := proto.Clone(in).(*UpdateDefaultSlaveRuntimeConfigRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateDefaultSlaveRuntimeConfigRequest. Required by controller-gen.
func (in *UpdateDefaultSlaveRuntimeConfigRequest) DeepCopy() *UpdateDefaultSlaveRuntimeConfigRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateDefaultSlaveRuntimeConfigRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateDefaultSlaveRuntimeConfigRequest. Required by controller-gen.
func (in *UpdateDefaultSlaveRuntimeConfigRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateDefaultSlaveRuntimeConfigResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateDefaultSlaveRuntimeConfigResponse) DeepCopyInto(out *UpdateDefaultSlaveRuntimeConfigResponse) {
	p := proto.Clone(in).(*UpdateDefaultSlaveRuntimeConfigResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateDefaultSlaveRuntimeConfigResponse. Required by controller-gen.
func (in *UpdateDefaultSlaveRuntimeConfigResponse) DeepCopy() *UpdateDefaultSlaveRuntimeConfigResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateDefaultSlaveRuntimeConfigResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateDefaultSlaveRuntimeConfigResponse. Required by controller-gen.
func (in *UpdateDefaultSlaveRuntimeConfigResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlaveRuntimeConfigWithAddress within kubernetes types, where deepcopy-gen is used.
func (in *SlaveRuntimeConfigWithAddress) DeepCopyInto(out *SlaveRuntimeConfigWithAddress) {
	p := proto.Clone(in).(*SlaveRuntimeConfigWithAddress)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlaveRuntimeConfigWithAddress. Required by controller-gen.
func (in *SlaveRuntimeConfigWithAddress) DeepCopy() *SlaveRuntimeConfigWithAddress {
	if in == nil {
		return nil
	}
	out := new(SlaveRuntimeConfigWithAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlaveRuntimeConfigWithAddress. Required by controller-gen.
func (in *SlaveRuntimeConfigWithAddress) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetDefaultSlaveRuntimeConfigRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetDefaultSlaveRuntimeConfigRequest) DeepCopyInto(out *GetDefaultSlaveRuntimeConfigRequest) {
	p := proto.Clone(in).(*GetDefaultSlaveRuntimeConfigRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetDefaultSlaveRuntimeConfigRequest. Required by controller-gen.
func (in *GetDefaultSlaveRuntimeConfigRequest) DeepCopy() *GetDefaultSlaveRuntimeConfigRequest {
	if in == nil {
		return nil
	}
	out := new(GetDefaultSlaveRuntimeConfigRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetDefaultSlaveRuntimeConfigRequest. Required by controller-gen.
func (in *GetDefaultSlaveRuntimeConfigRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetDefaultSlaveRuntimeConfigResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetDefaultSlaveRuntimeConfigResponse) DeepCopyInto(out *GetDefaultSlaveRuntimeConfigResponse) {
	p := proto.Clone(in).(*GetDefaultSlaveRuntimeConfigResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetDefaultSlaveRuntimeConfigResponse. Required by controller-gen.
func (in *GetDefaultSlaveRuntimeConfigResponse) DeepCopy() *GetDefaultSlaveRuntimeConfigResponse {
	if in == nil {
		return nil
	}
	out := new(GetDefaultSlaveRuntimeConfigResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetDefaultSlaveRuntimeConfigResponse. Required by controller-gen.
func (in *GetDefaultSlaveRuntimeConfigResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateSlaveRuntimeConfigRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateSlaveRuntimeConfigRequest) DeepCopyInto(out *UpdateSlaveRuntimeConfigRequest) {
	p := proto.Clone(in).(*UpdateSlaveRuntimeConfigRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveRuntimeConfigRequest. Required by controller-gen.
func (in *UpdateSlaveRuntimeConfigRequest) DeepCopy() *UpdateSlaveRuntimeConfigRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateSlaveRuntimeConfigRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveRuntimeConfigRequest. Required by controller-gen.
func (in *UpdateSlaveRuntimeConfigRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateSlaveRuntimeConfigResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateSlaveRuntimeConfigResponse) DeepCopyInto(out *UpdateSlaveRuntimeConfigResponse) {
	p := proto.Clone(in).(*UpdateSlaveRuntimeConfigResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveRuntimeConfigResponse. Required by controller-gen.
func (in *UpdateSlaveRuntimeConfigResponse) DeepCopy() *UpdateSlaveRuntimeConfigResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateSlaveRuntimeConfigResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveRuntimeConfigResponse. Required by controller-gen.
func (in *UpdateSlaveRuntimeConfigResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteSlaveRuntimeConfigRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteSlaveRuntimeConfigRequest) DeepCopyInto(out *DeleteSlaveRuntimeConfigRequest) {
	p := proto.Clone(in).(*DeleteSlaveRuntimeConfigRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteSlaveRuntimeConfigRequest. Required by controller-gen.
func (in *DeleteSlaveRuntimeConfigRequest) DeepCopy() *DeleteSlaveRuntimeConfigRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteSlaveRuntimeConfigRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteSlaveRuntimeConfigRequest. Required by controller-gen.
func (in *DeleteSlaveRuntimeConfigRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteSlaveRuntimeConfigResponse within kubernetes types, where deepcopy-gen is used.
func (in *DeleteSlaveRuntimeConfigResponse) DeepCopyInto(out *DeleteSlaveRuntimeConfigResponse) {
	p := proto.Clone(in).(*DeleteSlaveRuntimeConfigResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteSlaveRuntimeConfigResponse. Required by controller-gen.
func (in *DeleteSlaveRuntimeConfigResponse) DeepCopy() *DeleteSlaveRuntimeConfigResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteSlaveRuntimeConfigResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteSlaveRuntimeConfigResponse. Required by controller-gen.
func (in *DeleteSlaveRuntimeConfigResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetSlaveRuntimeConfigRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetSlaveRuntimeConfigRequest) DeepCopyInto(out *GetSlaveRuntimeConfigRequest) {
	p := proto.Clone(in).(*GetSlaveRuntimeConfigRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetSlaveRuntimeConfigRequest. Required by controller-gen.
func (in *GetSlaveRuntimeConfigRequest) DeepCopy() *GetSlaveRuntimeConfigRequest {
	if in == nil {
		return nil
	}
	out := new(GetSlaveRuntimeConfigRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetSlaveRuntimeConfigRequest. Required by controller-gen.
func (in *GetSlaveRuntimeConfigRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetSlaveRuntimeConfigResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetSlaveRuntimeConfigResponse) DeepCopyInto(out *GetSlaveRuntimeConfigResponse) {
	p := proto.Clone(in).(*GetSlaveRuntimeConfigResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetSlaveRuntimeConfigResponse. Required by controller-gen.
func (in *GetSlaveRuntimeConfigResponse) DeepCopy() *GetSlaveRuntimeConfigResponse {
	if in == nil {
		return nil
	}
	out := new(GetSlaveRuntimeConfigResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetSlaveRuntimeConfigResponse. Required by controller-gen.
func (in *GetSlaveRuntimeConfigResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddLabelRequest within kubernetes types, where deepcopy-gen is used.
func (in *AddLabelRequest) DeepCopyInto(out *AddLabelRequest) {
	p := proto.Clone(in).(*AddLabelRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddLabelRequest. Required by controller-gen.
func (in *AddLabelRequest) DeepCopy() *AddLabelRequest {
	if in == nil {
		return nil
	}
	out := new(AddLabelRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddLabelRequest. Required by controller-gen.
func (in *AddLabelRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelLabelRequest within kubernetes types, where deepcopy-gen is used.
func (in *DelLabelRequest) DeepCopyInto(out *DelLabelRequest) {
	p := proto.Clone(in).(*DelLabelRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelLabelRequest. Required by controller-gen.
func (in *DelLabelRequest) DeepCopy() *DelLabelRequest {
	if in == nil {
		return nil
	}
	out := new(DelLabelRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelLabelRequest. Required by controller-gen.
func (in *DelLabelRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateLabelRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateLabelRequest) DeepCopyInto(out *UpdateLabelRequest) {
	p := proto.Clone(in).(*UpdateLabelRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateLabelRequest. Required by controller-gen.
func (in *UpdateLabelRequest) DeepCopy() *UpdateLabelRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateLabelRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateLabelRequest. Required by controller-gen.
func (in *UpdateLabelRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateSlaveLeaseRatioRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateSlaveLeaseRatioRequest) DeepCopyInto(out *UpdateSlaveLeaseRatioRequest) {
	p := proto.Clone(in).(*UpdateSlaveLeaseRatioRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveLeaseRatioRequest. Required by controller-gen.
func (in *UpdateSlaveLeaseRatioRequest) DeepCopy() *UpdateSlaveLeaseRatioRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateSlaveLeaseRatioRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveLeaseRatioRequest. Required by controller-gen.
func (in *UpdateSlaveLeaseRatioRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateSlaveVisibilityRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateSlaveVisibilityRequest) DeepCopyInto(out *UpdateSlaveVisibilityRequest) {
	p := proto.Clone(in).(*UpdateSlaveVisibilityRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveVisibilityRequest. Required by controller-gen.
func (in *UpdateSlaveVisibilityRequest) DeepCopy() *UpdateSlaveVisibilityRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateSlaveVisibilityRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveVisibilityRequest. Required by controller-gen.
func (in *UpdateSlaveVisibilityRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClearSlaveVisibilityRequest within kubernetes types, where deepcopy-gen is used.
func (in *ClearSlaveVisibilityRequest) DeepCopyInto(out *ClearSlaveVisibilityRequest) {
	p := proto.Clone(in).(*ClearSlaveVisibilityRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearSlaveVisibilityRequest. Required by controller-gen.
func (in *ClearSlaveVisibilityRequest) DeepCopy() *ClearSlaveVisibilityRequest {
	if in == nil {
		return nil
	}
	out := new(ClearSlaveVisibilityRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClearSlaveVisibilityRequest. Required by controller-gen.
func (in *ClearSlaveVisibilityRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddSlaveVisibilityRequest within kubernetes types, where deepcopy-gen is used.
func (in *AddSlaveVisibilityRequest) DeepCopyInto(out *AddSlaveVisibilityRequest) {
	p := proto.Clone(in).(*AddSlaveVisibilityRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddSlaveVisibilityRequest. Required by controller-gen.
func (in *AddSlaveVisibilityRequest) DeepCopy() *AddSlaveVisibilityRequest {
	if in == nil {
		return nil
	}
	out := new(AddSlaveVisibilityRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddSlaveVisibilityRequest. Required by controller-gen.
func (in *AddSlaveVisibilityRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelSlaveVisibilityRequest within kubernetes types, where deepcopy-gen is used.
func (in *DelSlaveVisibilityRequest) DeepCopyInto(out *DelSlaveVisibilityRequest) {
	p := proto.Clone(in).(*DelSlaveVisibilityRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelSlaveVisibilityRequest. Required by controller-gen.
func (in *DelSlaveVisibilityRequest) DeepCopy() *DelSlaveVisibilityRequest {
	if in == nil {
		return nil
	}
	out := new(DelSlaveVisibilityRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelSlaveVisibilityRequest. Required by controller-gen.
func (in *DelSlaveVisibilityRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateSlaveSchedDomainRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateSlaveSchedDomainRequest) DeepCopyInto(out *UpdateSlaveSchedDomainRequest) {
	p := proto.Clone(in).(*UpdateSlaveSchedDomainRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveSchedDomainRequest. Required by controller-gen.
func (in *UpdateSlaveSchedDomainRequest) DeepCopy() *UpdateSlaveSchedDomainRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateSlaveSchedDomainRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveSchedDomainRequest. Required by controller-gen.
func (in *UpdateSlaveSchedDomainRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateSlaveSchedulerRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateSlaveSchedulerRequest) DeepCopyInto(out *UpdateSlaveSchedulerRequest) {
	p := proto.Clone(in).(*UpdateSlaveSchedulerRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveSchedulerRequest. Required by controller-gen.
func (in *UpdateSlaveSchedulerRequest) DeepCopy() *UpdateSlaveSchedulerRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateSlaveSchedulerRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlaveSchedulerRequest. Required by controller-gen.
func (in *UpdateSlaveSchedulerRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddSlotPreferenceRequest within kubernetes types, where deepcopy-gen is used.
func (in *AddSlotPreferenceRequest) DeepCopyInto(out *AddSlotPreferenceRequest) {
	p := proto.Clone(in).(*AddSlotPreferenceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddSlotPreferenceRequest. Required by controller-gen.
func (in *AddSlotPreferenceRequest) DeepCopy() *AddSlotPreferenceRequest {
	if in == nil {
		return nil
	}
	out := new(AddSlotPreferenceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddSlotPreferenceRequest. Required by controller-gen.
func (in *AddSlotPreferenceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelSlotPreferenceRequest within kubernetes types, where deepcopy-gen is used.
func (in *DelSlotPreferenceRequest) DeepCopyInto(out *DelSlotPreferenceRequest) {
	p := proto.Clone(in).(*DelSlotPreferenceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelSlotPreferenceRequest. Required by controller-gen.
func (in *DelSlotPreferenceRequest) DeepCopy() *DelSlotPreferenceRequest {
	if in == nil {
		return nil
	}
	out := new(DelSlotPreferenceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelSlotPreferenceRequest. Required by controller-gen.
func (in *DelSlotPreferenceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateSlotPreferenceRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateSlotPreferenceRequest) DeepCopyInto(out *UpdateSlotPreferenceRequest) {
	p := proto.Clone(in).(*UpdateSlotPreferenceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlotPreferenceRequest. Required by controller-gen.
func (in *UpdateSlotPreferenceRequest) DeepCopy() *UpdateSlotPreferenceRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateSlotPreferenceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSlotPreferenceRequest. Required by controller-gen.
func (in *UpdateSlotPreferenceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClearSlotPreferenceRequest within kubernetes types, where deepcopy-gen is used.
func (in *ClearSlotPreferenceRequest) DeepCopyInto(out *ClearSlotPreferenceRequest) {
	p := proto.Clone(in).(*ClearSlotPreferenceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearSlotPreferenceRequest. Required by controller-gen.
func (in *ClearSlotPreferenceRequest) DeepCopy() *ClearSlotPreferenceRequest {
	if in == nil {
		return nil
	}
	out := new(ClearSlotPreferenceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClearSlotPreferenceRequest. Required by controller-gen.
func (in *ClearSlotPreferenceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateSyncOptionRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateSyncOptionRequest) DeepCopyInto(out *UpdateSyncOptionRequest) {
	p := proto.Clone(in).(*UpdateSyncOptionRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSyncOptionRequest. Required by controller-gen.
func (in *UpdateSyncOptionRequest) DeepCopy() *UpdateSyncOptionRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateSyncOptionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateSyncOptionRequest. Required by controller-gen.
func (in *UpdateSyncOptionRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
