// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ApplicationMaster.proto

package hippo

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using ReserveSlot within kubernetes types, where deepcopy-gen is used.
func (in *ReserveSlot) DeepCopyInto(out *ReserveSlot) {
	p := proto.Clone(in).(*ReserveSlot)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReserveSlot. Required by controller-gen.
func (in *ReserveSlot) DeepCopy() *ReserveSlot {
	if in == nil {
		return nil
	}
	out := new(ReserveSlot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ReserveSlot. Required by controller-gen.
func (in *ReserveSlot) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AllocateRequest within kubernetes types, where deepcopy-gen is used.
func (in *AllocateRequest) DeepCopyInto(out *AllocateRequest) {
	p := proto.Clone(in).(*AllocateRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocateRequest. Required by controller-gen.
func (in *AllocateRequest) DeepCopy() *AllocateRequest {
	if in == nil {
		return nil
	}
	out := new(AllocateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AllocateRequest. Required by controller-gen.
func (in *AllocateRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AllocateResponse within kubernetes types, where deepcopy-gen is used.
func (in *AllocateResponse) DeepCopyInto(out *AllocateResponse) {
	p := proto.Clone(in).(*AllocateResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocateResponse. Required by controller-gen.
func (in *AllocateResponse) DeepCopy() *AllocateResponse {
	if in == nil {
		return nil
	}
	out := new(AllocateResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AllocateResponse. Required by controller-gen.
func (in *AllocateResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
