// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ApplicationMaster.proto

package hippo

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ReserveSlot struct {
	SlotId               *SlotId  `protobuf:"bytes,1,opt,name=slotId" json:"slotId,omitempty"`
	ReserveTime          *int32   `protobuf:"varint,2,opt,name=reserveTime,def=0" json:"reserveTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveSlot) Reset()         { *m = ReserveSlot{} }
func (m *ReserveSlot) String() string { return proto.CompactTextString(m) }
func (*ReserveSlot) ProtoMessage()    {}
func (*ReserveSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_d03180f5fb8dbd07, []int{0}
}
func (m *ReserveSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveSlot.Unmarshal(m, b)
}
func (m *ReserveSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveSlot.Marshal(b, m, deterministic)
}
func (m *ReserveSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveSlot.Merge(m, src)
}
func (m *ReserveSlot) XXX_Size() int {
	return xxx_messageInfo_ReserveSlot.Size(m)
}
func (m *ReserveSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveSlot.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveSlot proto.InternalMessageInfo

const Default_ReserveSlot_ReserveTime int32 = 0

func (m *ReserveSlot) GetSlotId() *SlotId {
	if m != nil {
		return m.SlotId
	}
	return nil
}

func (m *ReserveSlot) GetReserveTime() int32 {
	if m != nil && m.ReserveTime != nil {
		return *m.ReserveTime
	}
	return Default_ReserveSlot_ReserveTime
}

type AllocateRequest struct {
	ApplicationId        *string                  `protobuf:"bytes,1,opt,name=applicationId" json:"applicationId,omitempty"`
	Require              []*ResourceRequest       `protobuf:"bytes,2,rep,name=require" json:"require,omitempty"`
	Release              []*SlotId                `protobuf:"bytes,3,rep,name=release" json:"release,omitempty"`
	PreferenceDesc       []*PreferenceDescription `protobuf:"bytes,4,rep,name=preferenceDesc" json:"preferenceDesc,omitempty"`
	Queue                *string                  `protobuf:"bytes,5,opt,name=queue" json:"queue,omitempty"`
	SlotPayloads         []*SlotPayload           `protobuf:"bytes,6,rep,name=slotPayloads" json:"slotPayloads,omitempty"`
	ReserveSlot          []*ReserveSlot           `protobuf:"bytes,7,rep,name=reserveSlot" json:"reserveSlot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AllocateRequest) Reset()         { *m = AllocateRequest{} }
func (m *AllocateRequest) String() string { return proto.CompactTextString(m) }
func (*AllocateRequest) ProtoMessage()    {}
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d03180f5fb8dbd07, []int{1}
}
func (m *AllocateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocateRequest.Unmarshal(m, b)
}
func (m *AllocateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocateRequest.Marshal(b, m, deterministic)
}
func (m *AllocateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocateRequest.Merge(m, src)
}
func (m *AllocateRequest) XXX_Size() int {
	return xxx_messageInfo_AllocateRequest.Size(m)
}
func (m *AllocateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllocateRequest proto.InternalMessageInfo

func (m *AllocateRequest) GetApplicationId() string {
	if m != nil && m.ApplicationId != nil {
		return *m.ApplicationId
	}
	return ""
}

func (m *AllocateRequest) GetRequire() []*ResourceRequest {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *AllocateRequest) GetRelease() []*SlotId {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *AllocateRequest) GetPreferenceDesc() []*PreferenceDescription {
	if m != nil {
		return m.PreferenceDesc
	}
	return nil
}

func (m *AllocateRequest) GetQueue() string {
	if m != nil && m.Queue != nil {
		return *m.Queue
	}
	return ""
}

func (m *AllocateRequest) GetSlotPayloads() []*SlotPayload {
	if m != nil {
		return m.SlotPayloads
	}
	return nil
}

func (m *AllocateRequest) GetReserveSlot() []*ReserveSlot {
	if m != nil {
		return m.ReserveSlot
	}
	return nil
}

type AllocateResponse struct {
	AssignedResources    []*ResourceResponse `protobuf:"bytes,1,rep,name=assignedResources" json:"assignedResources,omitempty"`
	ErrorInfo            *ErrorInfo          `protobuf:"bytes,2,opt,name=errorInfo" json:"errorInfo,omitempty"`
	Labels               []*Parameter        `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AllocateResponse) Reset()         { *m = AllocateResponse{} }
func (m *AllocateResponse) String() string { return proto.CompactTextString(m) }
func (*AllocateResponse) ProtoMessage()    {}
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d03180f5fb8dbd07, []int{2}
}
func (m *AllocateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocateResponse.Unmarshal(m, b)
}
func (m *AllocateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocateResponse.Marshal(b, m, deterministic)
}
func (m *AllocateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocateResponse.Merge(m, src)
}
func (m *AllocateResponse) XXX_Size() int {
	return xxx_messageInfo_AllocateResponse.Size(m)
}
func (m *AllocateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllocateResponse proto.InternalMessageInfo

func (m *AllocateResponse) GetAssignedResources() []*ResourceResponse {
	if m != nil {
		return m.AssignedResources
	}
	return nil
}

func (m *AllocateResponse) GetErrorInfo() *ErrorInfo {
	if m != nil {
		return m.ErrorInfo
	}
	return nil
}

func (m *AllocateResponse) GetLabels() []*Parameter {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*ReserveSlot)(nil), "hippo.ReserveSlot")
	proto.RegisterType((*AllocateRequest)(nil), "hippo.AllocateRequest")
	proto.RegisterType((*AllocateResponse)(nil), "hippo.AllocateResponse")
}

func init() { proto.RegisterFile("ApplicationMaster.proto", fileDescriptor_d03180f5fb8dbd07) }

var fileDescriptor_d03180f5fb8dbd07 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4e, 0xea, 0x40,
	0x18, 0x85, 0x53, 0xb8, 0x85, 0x30, 0x85, 0x7b, 0xb9, 0x13, 0x23, 0x13, 0xe3, 0x82, 0xa0, 0xc6,
	0xae, 0x1a, 0x42, 0x8c, 0x0b, 0x77, 0x44, 0x58, 0xb0, 0x30, 0x21, 0x83, 0x1b, 0x97, 0x63, 0xf9,
	0xd1, 0x26, 0xd3, 0xce, 0x30, 0x33, 0x35, 0xf1, 0xb9, 0x7c, 0x1d, 0x1f, 0xc6, 0x74, 0x3a, 0x95,
	0x16, 0x96, 0x3d, 0xe7, 0x7c, 0x7f, 0x4f, 0xce, 0xa0, 0xd1, 0x5c, 0x4a, 0x9e, 0xc4, 0xcc, 0x24,
	0x22, 0x7b, 0x62, 0xda, 0x80, 0x8a, 0xa4, 0x12, 0x46, 0x60, 0xff, 0x3d, 0x91, 0x52, 0x5c, 0xf4,
	0x1f, 0x45, 0x9a, 0x8a, 0xac, 0x14, 0x27, 0x2f, 0x28, 0xa0, 0xa0, 0x41, 0x7d, 0xc0, 0x86, 0x0b,
	0x83, 0x6f, 0x50, 0x47, 0x73, 0x61, 0x56, 0x5b, 0xe2, 0x8d, 0xbd, 0x30, 0x98, 0x0d, 0x22, 0x0b,
	0x45, 0x1b, 0x2b, 0x52, 0x67, 0xe2, 0x2b, 0x14, 0xa8, 0x92, 0x7a, 0x4e, 0x52, 0x20, 0xad, 0xb1,
	0x17, 0xfa, 0x0f, 0xde, 0x94, 0xd6, 0xd5, 0xc9, 0x77, 0x0b, 0xfd, 0x9b, 0x73, 0x2e, 0x62, 0x66,
	0x80, 0xc2, 0x3e, 0x07, 0x6d, 0xf0, 0x35, 0x1a, 0xb0, 0x43, 0x3d, 0xf7, 0x9b, 0x1e, 0x6d, 0x8a,
	0x78, 0x8a, 0xba, 0x0a, 0xf6, 0x79, 0xa2, 0x8a, 0xd3, 0xed, 0x30, 0x98, 0x9d, 0xbb, 0x1a, 0x14,
	0xb4, 0xc8, 0x55, 0x5c, 0x9d, 0xa3, 0x55, 0x0c, 0xdf, 0x16, 0x04, 0x07, 0xa6, 0x81, 0xb4, 0x2d,
	0x71, 0x54, 0xbc, 0x72, 0xf1, 0x02, 0xfd, 0x95, 0x0a, 0x76, 0xa0, 0x20, 0x8b, 0x61, 0x01, 0x3a,
	0x26, 0x7f, 0x6c, 0xfe, 0xd2, 0xe5, 0xd7, 0x0d, 0x53, 0x25, 0xb2, 0xa8, 0x44, 0x8f, 0x18, 0x7c,
	0x86, 0xfc, 0x7d, 0x0e, 0x39, 0x10, 0xdf, 0xd6, 0x2f, 0x3f, 0xf0, 0x3d, 0xea, 0x17, 0xfb, 0xac,
	0xd9, 0x27, 0x17, 0x6c, 0xab, 0x49, 0xc7, 0x5e, 0xc6, 0xb5, 0x26, 0xce, 0xa2, 0x8d, 0x1c, 0xbe,
	0xfb, 0x5d, 0xb3, 0xc8, 0x90, 0x6e, 0x03, 0xab, 0xbd, 0x0e, 0xad, 0xc7, 0x26, 0x5f, 0x1e, 0x1a,
	0x1e, 0xe6, 0xd5, 0x52, 0x64, 0x1a, 0xf0, 0x12, 0xfd, 0x67, 0x5a, 0x27, 0x6f, 0x19, 0x6c, 0xab,
	0xad, 0x34, 0xf1, 0xec, 0xc1, 0xd1, 0xc9, 0x86, 0x25, 0x43, 0x4f, 0x09, 0x1c, 0xa1, 0x1e, 0x28,
	0x25, 0xd4, 0x2a, 0xdb, 0x09, 0xfb, 0xba, 0xc1, 0x6c, 0xe8, 0xf0, 0x65, 0xa5, 0xd3, 0x43, 0x04,
	0x87, 0xa8, 0xc3, 0xd9, 0x2b, 0x70, 0xed, 0xd6, 0xaf, 0xc2, 0x6b, 0xa6, 0x58, 0x0a, 0x06, 0x14,
	0x75, 0xfe, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x0b, 0x3e, 0x8d, 0x9e, 0x02, 0x00, 0x00,
}
