// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: Client.proto

package hippo

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using UpdateMappingRuleRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateMappingRuleRequest) DeepCopyInto(out *UpdateMappingRuleRequest) {
	p := proto.Clone(in).(*UpdateMappingRuleRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMappingRuleRequest. Required by controller-gen.
func (in *UpdateMappingRuleRequest) DeepCopy() *UpdateMappingRuleRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateMappingRuleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMappingRuleRequest. Required by controller-gen.
func (in *UpdateMappingRuleRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateMappingRuleResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateMappingRuleResponse) DeepCopyInto(out *UpdateMappingRuleResponse) {
	p := proto.Clone(in).(*UpdateMappingRuleResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMappingRuleResponse. Required by controller-gen.
func (in *UpdateMappingRuleResponse) DeepCopy() *UpdateMappingRuleResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateMappingRuleResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMappingRuleResponse. Required by controller-gen.
func (in *UpdateMappingRuleResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetMappingRulesRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetMappingRulesRequest) DeepCopyInto(out *GetMappingRulesRequest) {
	p := proto.Clone(in).(*GetMappingRulesRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetMappingRulesRequest. Required by controller-gen.
func (in *GetMappingRulesRequest) DeepCopy() *GetMappingRulesRequest {
	if in == nil {
		return nil
	}
	out := new(GetMappingRulesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetMappingRulesRequest. Required by controller-gen.
func (in *GetMappingRulesRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetMappingRulesResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetMappingRulesResponse) DeepCopyInto(out *GetMappingRulesResponse) {
	p := proto.Clone(in).(*GetMappingRulesResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetMappingRulesResponse. Required by controller-gen.
func (in *GetMappingRulesResponse) DeepCopy() *GetMappingRulesResponse {
	if in == nil {
		return nil
	}
	out := new(GetMappingRulesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetMappingRulesResponse. Required by controller-gen.
func (in *GetMappingRulesResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelMappingRuleRequest within kubernetes types, where deepcopy-gen is used.
func (in *DelMappingRuleRequest) DeepCopyInto(out *DelMappingRuleRequest) {
	p := proto.Clone(in).(*DelMappingRuleRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelMappingRuleRequest. Required by controller-gen.
func (in *DelMappingRuleRequest) DeepCopy() *DelMappingRuleRequest {
	if in == nil {
		return nil
	}
	out := new(DelMappingRuleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelMappingRuleRequest. Required by controller-gen.
func (in *DelMappingRuleRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelMappingRuleResponse within kubernetes types, where deepcopy-gen is used.
func (in *DelMappingRuleResponse) DeepCopyInto(out *DelMappingRuleResponse) {
	p := proto.Clone(in).(*DelMappingRuleResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelMappingRuleResponse. Required by controller-gen.
func (in *DelMappingRuleResponse) DeepCopy() *DelMappingRuleResponse {
	if in == nil {
		return nil
	}
	out := new(DelMappingRuleResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelMappingRuleResponse. Required by controller-gen.
func (in *DelMappingRuleResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateRulesRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateRulesRequest) DeepCopyInto(out *UpdateRulesRequest) {
	p := proto.Clone(in).(*UpdateRulesRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateRulesRequest. Required by controller-gen.
func (in *UpdateRulesRequest) DeepCopy() *UpdateRulesRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateRulesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateRulesRequest. Required by controller-gen.
func (in *UpdateRulesRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateRulesResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateRulesResponse) DeepCopyInto(out *UpdateRulesResponse) {
	p := proto.Clone(in).(*UpdateRulesResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateRulesResponse. Required by controller-gen.
func (in *UpdateRulesResponse) DeepCopy() *UpdateRulesResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateRulesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateRulesResponse. Required by controller-gen.
func (in *UpdateRulesResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetRulesRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetRulesRequest) DeepCopyInto(out *GetRulesRequest) {
	p := proto.Clone(in).(*GetRulesRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRulesRequest. Required by controller-gen.
func (in *GetRulesRequest) DeepCopy() *GetRulesRequest {
	if in == nil {
		return nil
	}
	out := new(GetRulesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetRulesRequest. Required by controller-gen.
func (in *GetRulesRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetRulesResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetRulesResponse) DeepCopyInto(out *GetRulesResponse) {
	p := proto.Clone(in).(*GetRulesResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRulesResponse. Required by controller-gen.
func (in *GetRulesResponse) DeepCopy() *GetRulesResponse {
	if in == nil {
		return nil
	}
	out := new(GetRulesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetRulesResponse. Required by controller-gen.
func (in *GetRulesResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddQueueRequest within kubernetes types, where deepcopy-gen is used.
func (in *AddQueueRequest) DeepCopyInto(out *AddQueueRequest) {
	p := proto.Clone(in).(*AddQueueRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddQueueRequest. Required by controller-gen.
func (in *AddQueueRequest) DeepCopy() *AddQueueRequest {
	if in == nil {
		return nil
	}
	out := new(AddQueueRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddQueueRequest. Required by controller-gen.
func (in *AddQueueRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddQueueResponse within kubernetes types, where deepcopy-gen is used.
func (in *AddQueueResponse) DeepCopyInto(out *AddQueueResponse) {
	p := proto.Clone(in).(*AddQueueResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddQueueResponse. Required by controller-gen.
func (in *AddQueueResponse) DeepCopy() *AddQueueResponse {
	if in == nil {
		return nil
	}
	out := new(AddQueueResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddQueueResponse. Required by controller-gen.
func (in *AddQueueResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelQueueRequest within kubernetes types, where deepcopy-gen is used.
func (in *DelQueueRequest) DeepCopyInto(out *DelQueueRequest) {
	p := proto.Clone(in).(*DelQueueRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelQueueRequest. Required by controller-gen.
func (in *DelQueueRequest) DeepCopy() *DelQueueRequest {
	if in == nil {
		return nil
	}
	out := new(DelQueueRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelQueueRequest. Required by controller-gen.
func (in *DelQueueRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelQueueResponse within kubernetes types, where deepcopy-gen is used.
func (in *DelQueueResponse) DeepCopyInto(out *DelQueueResponse) {
	p := proto.Clone(in).(*DelQueueResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelQueueResponse. Required by controller-gen.
func (in *DelQueueResponse) DeepCopy() *DelQueueResponse {
	if in == nil {
		return nil
	}
	out := new(DelQueueResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelQueueResponse. Required by controller-gen.
func (in *DelQueueResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateQueueRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateQueueRequest) DeepCopyInto(out *UpdateQueueRequest) {
	p := proto.Clone(in).(*UpdateQueueRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateQueueRequest. Required by controller-gen.
func (in *UpdateQueueRequest) DeepCopy() *UpdateQueueRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateQueueRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateQueueRequest. Required by controller-gen.
func (in *UpdateQueueRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateQueueResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateQueueResponse) DeepCopyInto(out *UpdateQueueResponse) {
	p := proto.Clone(in).(*UpdateQueueResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateQueueResponse. Required by controller-gen.
func (in *UpdateQueueResponse) DeepCopy() *UpdateQueueResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateQueueResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateQueueResponse. Required by controller-gen.
func (in *UpdateQueueResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using QueueStatusRequest within kubernetes types, where deepcopy-gen is used.
func (in *QueueStatusRequest) DeepCopyInto(out *QueueStatusRequest) {
	p := proto.Clone(in).(*QueueStatusRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueStatusRequest. Required by controller-gen.
func (in *QueueStatusRequest) DeepCopy() *QueueStatusRequest {
	if in == nil {
		return nil
	}
	out := new(QueueStatusRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new QueueStatusRequest. Required by controller-gen.
func (in *QueueStatusRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using QueueStatusResponse within kubernetes types, where deepcopy-gen is used.
func (in *QueueStatusResponse) DeepCopyInto(out *QueueStatusResponse) {
	p := proto.Clone(in).(*QueueStatusResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueStatusResponse. Required by controller-gen.
func (in *QueueStatusResponse) DeepCopy() *QueueStatusResponse {
	if in == nil {
		return nil
	}
	out := new(QueueStatusResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new QueueStatusResponse. Required by controller-gen.
func (in *QueueStatusResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MergeQueueRequest within kubernetes types, where deepcopy-gen is used.
func (in *MergeQueueRequest) DeepCopyInto(out *MergeQueueRequest) {
	p := proto.Clone(in).(*MergeQueueRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeQueueRequest. Required by controller-gen.
func (in *MergeQueueRequest) DeepCopy() *MergeQueueRequest {
	if in == nil {
		return nil
	}
	out := new(MergeQueueRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MergeQueueRequest. Required by controller-gen.
func (in *MergeQueueRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MergeQueueResponse within kubernetes types, where deepcopy-gen is used.
func (in *MergeQueueResponse) DeepCopyInto(out *MergeQueueResponse) {
	p := proto.Clone(in).(*MergeQueueResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeQueueResponse. Required by controller-gen.
func (in *MergeQueueResponse) DeepCopy() *MergeQueueResponse {
	if in == nil {
		return nil
	}
	out := new(MergeQueueResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MergeQueueResponse. Required by controller-gen.
func (in *MergeQueueResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListMergedQueuesRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListMergedQueuesRequest) DeepCopyInto(out *ListMergedQueuesRequest) {
	p := proto.Clone(in).(*ListMergedQueuesRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListMergedQueuesRequest. Required by controller-gen.
func (in *ListMergedQueuesRequest) DeepCopy() *ListMergedQueuesRequest {
	if in == nil {
		return nil
	}
	out := new(ListMergedQueuesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListMergedQueuesRequest. Required by controller-gen.
func (in *ListMergedQueuesRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MergedQueue within kubernetes types, where deepcopy-gen is used.
func (in *MergedQueue) DeepCopyInto(out *MergedQueue) {
	p := proto.Clone(in).(*MergedQueue)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergedQueue. Required by controller-gen.
func (in *MergedQueue) DeepCopy() *MergedQueue {
	if in == nil {
		return nil
	}
	out := new(MergedQueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MergedQueue. Required by controller-gen.
func (in *MergedQueue) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListMergedQueuesResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListMergedQueuesResponse) DeepCopyInto(out *ListMergedQueuesResponse) {
	p := proto.Clone(in).(*ListMergedQueuesResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListMergedQueuesResponse. Required by controller-gen.
func (in *ListMergedQueuesResponse) DeepCopy() *ListMergedQueuesResponse {
	if in == nil {
		return nil
	}
	out := new(ListMergedQueuesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListMergedQueuesResponse. Required by controller-gen.
func (in *ListMergedQueuesResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SubmitApplicationRequest within kubernetes types, where deepcopy-gen is used.
func (in *SubmitApplicationRequest) DeepCopyInto(out *SubmitApplicationRequest) {
	p := proto.Clone(in).(*SubmitApplicationRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubmitApplicationRequest. Required by controller-gen.
func (in *SubmitApplicationRequest) DeepCopy() *SubmitApplicationRequest {
	if in == nil {
		return nil
	}
	out := new(SubmitApplicationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SubmitApplicationRequest. Required by controller-gen.
func (in *SubmitApplicationRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SubmitApplicationResponse within kubernetes types, where deepcopy-gen is used.
func (in *SubmitApplicationResponse) DeepCopyInto(out *SubmitApplicationResponse) {
	p := proto.Clone(in).(*SubmitApplicationResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubmitApplicationResponse. Required by controller-gen.
func (in *SubmitApplicationResponse) DeepCopy() *SubmitApplicationResponse {
	if in == nil {
		return nil
	}
	out := new(SubmitApplicationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SubmitApplicationResponse. Required by controller-gen.
func (in *SubmitApplicationResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using StopApplicationRequest within kubernetes types, where deepcopy-gen is used.
func (in *StopApplicationRequest) DeepCopyInto(out *StopApplicationRequest) {
	p := proto.Clone(in).(*StopApplicationRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopApplicationRequest. Required by controller-gen.
func (in *StopApplicationRequest) DeepCopy() *StopApplicationRequest {
	if in == nil {
		return nil
	}
	out := new(StopApplicationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new StopApplicationRequest. Required by controller-gen.
func (in *StopApplicationRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using StopApplicationResponse within kubernetes types, where deepcopy-gen is used.
func (in *StopApplicationResponse) DeepCopyInto(out *StopApplicationResponse) {
	p := proto.Clone(in).(*StopApplicationResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopApplicationResponse. Required by controller-gen.
func (in *StopApplicationResponse) DeepCopy() *StopApplicationResponse {
	if in == nil {
		return nil
	}
	out := new(StopApplicationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new StopApplicationResponse. Required by controller-gen.
func (in *StopApplicationResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using FreezeApplicationRequest within kubernetes types, where deepcopy-gen is used.
func (in *FreezeApplicationRequest) DeepCopyInto(out *FreezeApplicationRequest) {
	p := proto.Clone(in).(*FreezeApplicationRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreezeApplicationRequest. Required by controller-gen.
func (in *FreezeApplicationRequest) DeepCopy() *FreezeApplicationRequest {
	if in == nil {
		return nil
	}
	out := new(FreezeApplicationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new FreezeApplicationRequest. Required by controller-gen.
func (in *FreezeApplicationRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using FreezeApplicationResponse within kubernetes types, where deepcopy-gen is used.
func (in *FreezeApplicationResponse) DeepCopyInto(out *FreezeApplicationResponse) {
	p := proto.Clone(in).(*FreezeApplicationResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreezeApplicationResponse. Required by controller-gen.
func (in *FreezeApplicationResponse) DeepCopy() *FreezeApplicationResponse {
	if in == nil {
		return nil
	}
	out := new(FreezeApplicationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new FreezeApplicationResponse. Required by controller-gen.
func (in *FreezeApplicationResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using FreezeAllApplicationRequest within kubernetes types, where deepcopy-gen is used.
func (in *FreezeAllApplicationRequest) DeepCopyInto(out *FreezeAllApplicationRequest) {
	p := proto.Clone(in).(*FreezeAllApplicationRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreezeAllApplicationRequest. Required by controller-gen.
func (in *FreezeAllApplicationRequest) DeepCopy() *FreezeAllApplicationRequest {
	if in == nil {
		return nil
	}
	out := new(FreezeAllApplicationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new FreezeAllApplicationRequest. Required by controller-gen.
func (in *FreezeAllApplicationRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using FreezeAllApplicationResponse within kubernetes types, where deepcopy-gen is used.
func (in *FreezeAllApplicationResponse) DeepCopyInto(out *FreezeAllApplicationResponse) {
	p := proto.Clone(in).(*FreezeAllApplicationResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreezeAllApplicationResponse. Required by controller-gen.
func (in *FreezeAllApplicationResponse) DeepCopy() *FreezeAllApplicationResponse {
	if in == nil {
		return nil
	}
	out := new(FreezeAllApplicationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new FreezeAllApplicationResponse. Required by controller-gen.
func (in *FreezeAllApplicationResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UnFreezeApplicationRequest within kubernetes types, where deepcopy-gen is used.
func (in *UnFreezeApplicationRequest) DeepCopyInto(out *UnFreezeApplicationRequest) {
	p := proto.Clone(in).(*UnFreezeApplicationRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnFreezeApplicationRequest. Required by controller-gen.
func (in *UnFreezeApplicationRequest) DeepCopy() *UnFreezeApplicationRequest {
	if in == nil {
		return nil
	}
	out := new(UnFreezeApplicationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UnFreezeApplicationRequest. Required by controller-gen.
func (in *UnFreezeApplicationRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UnFreezeApplicationResponse within kubernetes types, where deepcopy-gen is used.
func (in *UnFreezeApplicationResponse) DeepCopyInto(out *UnFreezeApplicationResponse) {
	p := proto.Clone(in).(*UnFreezeApplicationResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnFreezeApplicationResponse. Required by controller-gen.
func (in *UnFreezeApplicationResponse) DeepCopy() *UnFreezeApplicationResponse {
	if in == nil {
		return nil
	}
	out := new(UnFreezeApplicationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UnFreezeApplicationResponse. Required by controller-gen.
func (in *UnFreezeApplicationResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UnFreezeAllApplicationRequest within kubernetes types, where deepcopy-gen is used.
func (in *UnFreezeAllApplicationRequest) DeepCopyInto(out *UnFreezeAllApplicationRequest) {
	p := proto.Clone(in).(*UnFreezeAllApplicationRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnFreezeAllApplicationRequest. Required by controller-gen.
func (in *UnFreezeAllApplicationRequest) DeepCopy() *UnFreezeAllApplicationRequest {
	if in == nil {
		return nil
	}
	out := new(UnFreezeAllApplicationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UnFreezeAllApplicationRequest. Required by controller-gen.
func (in *UnFreezeAllApplicationRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UnFreezeAllApplicationResponse within kubernetes types, where deepcopy-gen is used.
func (in *UnFreezeAllApplicationResponse) DeepCopyInto(out *UnFreezeAllApplicationResponse) {
	p := proto.Clone(in).(*UnFreezeAllApplicationResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnFreezeAllApplicationResponse. Required by controller-gen.
func (in *UnFreezeAllApplicationResponse) DeepCopy() *UnFreezeAllApplicationResponse {
	if in == nil {
		return nil
	}
	out := new(UnFreezeAllApplicationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UnFreezeAllApplicationResponse. Required by controller-gen.
func (in *UnFreezeAllApplicationResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ForceKillApplicationRequest within kubernetes types, where deepcopy-gen is used.
func (in *ForceKillApplicationRequest) DeepCopyInto(out *ForceKillApplicationRequest) {
	p := proto.Clone(in).(*ForceKillApplicationRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForceKillApplicationRequest. Required by controller-gen.
func (in *ForceKillApplicationRequest) DeepCopy() *ForceKillApplicationRequest {
	if in == nil {
		return nil
	}
	out := new(ForceKillApplicationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ForceKillApplicationRequest. Required by controller-gen.
func (in *ForceKillApplicationRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ForceKillApplicationResponse within kubernetes types, where deepcopy-gen is used.
func (in *ForceKillApplicationResponse) DeepCopyInto(out *ForceKillApplicationResponse) {
	p := proto.Clone(in).(*ForceKillApplicationResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForceKillApplicationResponse. Required by controller-gen.
func (in *ForceKillApplicationResponse) DeepCopy() *ForceKillApplicationResponse {
	if in == nil {
		return nil
	}
	out := new(ForceKillApplicationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ForceKillApplicationResponse. Required by controller-gen.
func (in *ForceKillApplicationResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClearYarnApplicationIdRequest within kubernetes types, where deepcopy-gen is used.
func (in *ClearYarnApplicationIdRequest) DeepCopyInto(out *ClearYarnApplicationIdRequest) {
	p := proto.Clone(in).(*ClearYarnApplicationIdRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearYarnApplicationIdRequest. Required by controller-gen.
func (in *ClearYarnApplicationIdRequest) DeepCopy() *ClearYarnApplicationIdRequest {
	if in == nil {
		return nil
	}
	out := new(ClearYarnApplicationIdRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClearYarnApplicationIdRequest. Required by controller-gen.
func (in *ClearYarnApplicationIdRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClearYarnApplicationIdResponse within kubernetes types, where deepcopy-gen is used.
func (in *ClearYarnApplicationIdResponse) DeepCopyInto(out *ClearYarnApplicationIdResponse) {
	p := proto.Clone(in).(*ClearYarnApplicationIdResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearYarnApplicationIdResponse. Required by controller-gen.
func (in *ClearYarnApplicationIdResponse) DeepCopy() *ClearYarnApplicationIdResponse {
	if in == nil {
		return nil
	}
	out := new(ClearYarnApplicationIdResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClearYarnApplicationIdResponse. Required by controller-gen.
func (in *ClearYarnApplicationIdResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourcePreferenceRequest within kubernetes types, where deepcopy-gen is used.
func (in *ResourcePreferenceRequest) DeepCopyInto(out *ResourcePreferenceRequest) {
	p := proto.Clone(in).(*ResourcePreferenceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePreferenceRequest. Required by controller-gen.
func (in *ResourcePreferenceRequest) DeepCopy() *ResourcePreferenceRequest {
	if in == nil {
		return nil
	}
	out := new(ResourcePreferenceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePreferenceRequest. Required by controller-gen.
func (in *ResourcePreferenceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourcePreferenceResponse within kubernetes types, where deepcopy-gen is used.
func (in *ResourcePreferenceResponse) DeepCopyInto(out *ResourcePreferenceResponse) {
	p := proto.Clone(in).(*ResourcePreferenceResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePreferenceResponse. Required by controller-gen.
func (in *ResourcePreferenceResponse) DeepCopy() *ResourcePreferenceResponse {
	if in == nil {
		return nil
	}
	out := new(ResourcePreferenceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePreferenceResponse. Required by controller-gen.
func (in *ResourcePreferenceResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateResourcePreferenceRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateResourcePreferenceRequest) DeepCopyInto(out *UpdateResourcePreferenceRequest) {
	p := proto.Clone(in).(*UpdateResourcePreferenceRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourcePreferenceRequest. Required by controller-gen.
func (in *UpdateResourcePreferenceRequest) DeepCopy() *UpdateResourcePreferenceRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateResourcePreferenceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourcePreferenceRequest. Required by controller-gen.
func (in *UpdateResourcePreferenceRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateResourcePreferenceResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateResourcePreferenceResponse) DeepCopyInto(out *UpdateResourcePreferenceResponse) {
	p := proto.Clone(in).(*UpdateResourcePreferenceResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourcePreferenceResponse. Required by controller-gen.
func (in *UpdateResourcePreferenceResponse) DeepCopy() *UpdateResourcePreferenceResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateResourcePreferenceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourcePreferenceResponse. Required by controller-gen.
func (in *UpdateResourcePreferenceResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ServiceStatusRequest within kubernetes types, where deepcopy-gen is used.
func (in *ServiceStatusRequest) DeepCopyInto(out *ServiceStatusRequest) {
	p := proto.Clone(in).(*ServiceStatusRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatusRequest. Required by controller-gen.
func (in *ServiceStatusRequest) DeepCopy() *ServiceStatusRequest {
	if in == nil {
		return nil
	}
	out := new(ServiceStatusRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatusRequest. Required by controller-gen.
func (in *ServiceStatusRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ServiceStatusResponse within kubernetes types, where deepcopy-gen is used.
func (in *ServiceStatusResponse) DeepCopyInto(out *ServiceStatusResponse) {
	p := proto.Clone(in).(*ServiceStatusResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatusResponse. Required by controller-gen.
func (in *ServiceStatusResponse) DeepCopy() *ServiceStatusResponse {
	if in == nil {
		return nil
	}
	out := new(ServiceStatusResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatusResponse. Required by controller-gen.
func (in *ServiceStatusResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlaveStatusRequest within kubernetes types, where deepcopy-gen is used.
func (in *SlaveStatusRequest) DeepCopyInto(out *SlaveStatusRequest) {
	p := proto.Clone(in).(*SlaveStatusRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlaveStatusRequest. Required by controller-gen.
func (in *SlaveStatusRequest) DeepCopy() *SlaveStatusRequest {
	if in == nil {
		return nil
	}
	out := new(SlaveStatusRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlaveStatusRequest. Required by controller-gen.
func (in *SlaveStatusRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlaveStatusResponse within kubernetes types, where deepcopy-gen is used.
func (in *SlaveStatusResponse) DeepCopyInto(out *SlaveStatusResponse) {
	p := proto.Clone(in).(*SlaveStatusResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlaveStatusResponse. Required by controller-gen.
func (in *SlaveStatusResponse) DeepCopy() *SlaveStatusResponse {
	if in == nil {
		return nil
	}
	out := new(SlaveStatusResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlaveStatusResponse. Required by controller-gen.
func (in *SlaveStatusResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlaveAllocateWmarkRequest within kubernetes types, where deepcopy-gen is used.
func (in *SlaveAllocateWmarkRequest) DeepCopyInto(out *SlaveAllocateWmarkRequest) {
	p := proto.Clone(in).(*SlaveAllocateWmarkRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlaveAllocateWmarkRequest. Required by controller-gen.
func (in *SlaveAllocateWmarkRequest) DeepCopy() *SlaveAllocateWmarkRequest {
	if in == nil {
		return nil
	}
	out := new(SlaveAllocateWmarkRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlaveAllocateWmarkRequest. Required by controller-gen.
func (in *SlaveAllocateWmarkRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlaveAllocateWmarkResponse within kubernetes types, where deepcopy-gen is used.
func (in *SlaveAllocateWmarkResponse) DeepCopyInto(out *SlaveAllocateWmarkResponse) {
	p := proto.Clone(in).(*SlaveAllocateWmarkResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlaveAllocateWmarkResponse. Required by controller-gen.
func (in *SlaveAllocateWmarkResponse) DeepCopy() *SlaveAllocateWmarkResponse {
	if in == nil {
		return nil
	}
	out := new(SlaveAllocateWmarkResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlaveAllocateWmarkResponse. Required by controller-gen.
func (in *SlaveAllocateWmarkResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using QuotaSummaryRequest within kubernetes types, where deepcopy-gen is used.
func (in *QuotaSummaryRequest) DeepCopyInto(out *QuotaSummaryRequest) {
	p := proto.Clone(in).(*QuotaSummaryRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSummaryRequest. Required by controller-gen.
func (in *QuotaSummaryRequest) DeepCopy() *QuotaSummaryRequest {
	if in == nil {
		return nil
	}
	out := new(QuotaSummaryRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSummaryRequest. Required by controller-gen.
func (in *QuotaSummaryRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using QuotaSummaryResponse within kubernetes types, where deepcopy-gen is used.
func (in *QuotaSummaryResponse) DeepCopyInto(out *QuotaSummaryResponse) {
	p := proto.Clone(in).(*QuotaSummaryResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSummaryResponse. Required by controller-gen.
func (in *QuotaSummaryResponse) DeepCopy() *QuotaSummaryResponse {
	if in == nil {
		return nil
	}
	out := new(QuotaSummaryResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSummaryResponse. Required by controller-gen.
func (in *QuotaSummaryResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using QuotaSummary within kubernetes types, where deepcopy-gen is used.
func (in *QuotaSummary) DeepCopyInto(out *QuotaSummary) {
	p := proto.Clone(in).(*QuotaSummary)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSummary. Required by controller-gen.
func (in *QuotaSummary) DeepCopy() *QuotaSummary {
	if in == nil {
		return nil
	}
	out := new(QuotaSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSummary. Required by controller-gen.
func (in *QuotaSummary) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourceQuota within kubernetes types, where deepcopy-gen is used.
func (in *ResourceQuota) DeepCopyInto(out *ResourceQuota) {
	p := proto.Clone(in).(*ResourceQuota)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuota. Required by controller-gen.
func (in *ResourceQuota) DeepCopy() *ResourceQuota {
	if in == nil {
		return nil
	}
	out := new(ResourceQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuota. Required by controller-gen.
func (in *ResourceQuota) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppSummaryRequest within kubernetes types, where deepcopy-gen is used.
func (in *AppSummaryRequest) DeepCopyInto(out *AppSummaryRequest) {
	p := proto.Clone(in).(*AppSummaryRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSummaryRequest. Required by controller-gen.
func (in *AppSummaryRequest) DeepCopy() *AppSummaryRequest {
	if in == nil {
		return nil
	}
	out := new(AppSummaryRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppSummaryRequest. Required by controller-gen.
func (in *AppSummaryRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppSummaryResponse within kubernetes types, where deepcopy-gen is used.
func (in *AppSummaryResponse) DeepCopyInto(out *AppSummaryResponse) {
	p := proto.Clone(in).(*AppSummaryResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSummaryResponse. Required by controller-gen.
func (in *AppSummaryResponse) DeepCopy() *AppSummaryResponse {
	if in == nil {
		return nil
	}
	out := new(AppSummaryResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppSummaryResponse. Required by controller-gen.
func (in *AppSummaryResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppSummary within kubernetes types, where deepcopy-gen is used.
func (in *AppSummary) DeepCopyInto(out *AppSummary) {
	p := proto.Clone(in).(*AppSummary)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSummary. Required by controller-gen.
func (in *AppSummary) DeepCopy() *AppSummary {
	if in == nil {
		return nil
	}
	out := new(AppSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppSummary. Required by controller-gen.
func (in *AppSummary) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppRequireSummary within kubernetes types, where deepcopy-gen is used.
func (in *AppRequireSummary) DeepCopyInto(out *AppRequireSummary) {
	p := proto.Clone(in).(*AppRequireSummary)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRequireSummary. Required by controller-gen.
func (in *AppRequireSummary) DeepCopy() *AppRequireSummary {
	if in == nil {
		return nil
	}
	out := new(AppRequireSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppRequireSummary. Required by controller-gen.
func (in *AppRequireSummary) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppStatusRequest within kubernetes types, where deepcopy-gen is used.
func (in *AppStatusRequest) DeepCopyInto(out *AppStatusRequest) {
	p := proto.Clone(in).(*AppStatusRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppStatusRequest. Required by controller-gen.
func (in *AppStatusRequest) DeepCopy() *AppStatusRequest {
	if in == nil {
		return nil
	}
	out := new(AppStatusRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppStatusRequest. Required by controller-gen.
func (in *AppStatusRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppStatusResponse within kubernetes types, where deepcopy-gen is used.
func (in *AppStatusResponse) DeepCopyInto(out *AppStatusResponse) {
	p := proto.Clone(in).(*AppStatusResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppStatusResponse. Required by controller-gen.
func (in *AppStatusResponse) DeepCopy() *AppStatusResponse {
	if in == nil {
		return nil
	}
	out := new(AppStatusResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppStatusResponse. Required by controller-gen.
func (in *AppStatusResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppHistoryInfoRequest within kubernetes types, where deepcopy-gen is used.
func (in *AppHistoryInfoRequest) DeepCopyInto(out *AppHistoryInfoRequest) {
	p := proto.Clone(in).(*AppHistoryInfoRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppHistoryInfoRequest. Required by controller-gen.
func (in *AppHistoryInfoRequest) DeepCopy() *AppHistoryInfoRequest {
	if in == nil {
		return nil
	}
	out := new(AppHistoryInfoRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppHistoryInfoRequest. Required by controller-gen.
func (in *AppHistoryInfoRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AppHistoryInfoResponse within kubernetes types, where deepcopy-gen is used.
func (in *AppHistoryInfoResponse) DeepCopyInto(out *AppHistoryInfoResponse) {
	p := proto.Clone(in).(*AppHistoryInfoResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppHistoryInfoResponse. Required by controller-gen.
func (in *AppHistoryInfoResponse) DeepCopy() *AppHistoryInfoResponse {
	if in == nil {
		return nil
	}
	out := new(AppHistoryInfoResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AppHistoryInfoResponse. Required by controller-gen.
func (in *AppHistoryInfoResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using HistoryAppListResponse within kubernetes types, where deepcopy-gen is used.
func (in *HistoryAppListResponse) DeepCopyInto(out *HistoryAppListResponse) {
	p := proto.Clone(in).(*HistoryAppListResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HistoryAppListResponse. Required by controller-gen.
func (in *HistoryAppListResponse) DeepCopy() *HistoryAppListResponse {
	if in == nil {
		return nil
	}
	out := new(HistoryAppListResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new HistoryAppListResponse. Required by controller-gen.
func (in *HistoryAppListResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlaveNodeStatus within kubernetes types, where deepcopy-gen is used.
func (in *SlaveNodeStatus) DeepCopyInto(out *SlaveNodeStatus) {
	p := proto.Clone(in).(*SlaveNodeStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlaveNodeStatus. Required by controller-gen.
func (in *SlaveNodeStatus) DeepCopy() *SlaveNodeStatus {
	if in == nil {
		return nil
	}
	out := new(SlaveNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlaveNodeStatus. Required by controller-gen.
func (in *SlaveNodeStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlaveAllocateWmark within kubernetes types, where deepcopy-gen is used.
func (in *SlaveAllocateWmark) DeepCopyInto(out *SlaveAllocateWmark) {
	p := proto.Clone(in).(*SlaveAllocateWmark)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlaveAllocateWmark. Required by controller-gen.
func (in *SlaveAllocateWmark) DeepCopy() *SlaveAllocateWmark {
	if in == nil {
		return nil
	}
	out := new(SlaveAllocateWmark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlaveAllocateWmark. Required by controller-gen.
func (in *SlaveAllocateWmark) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlotStatus within kubernetes types, where deepcopy-gen is used.
func (in *SlotStatus) DeepCopyInto(out *SlotStatus) {
	p := proto.Clone(in).(*SlotStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlotStatus. Required by controller-gen.
func (in *SlotStatus) DeepCopy() *SlotStatus {
	if in == nil {
		return nil
	}
	out := new(SlotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlotStatus. Required by controller-gen.
func (in *SlotStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateApplicationRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateApplicationRequest) DeepCopyInto(out *UpdateApplicationRequest) {
	p := proto.Clone(in).(*UpdateApplicationRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateApplicationRequest. Required by controller-gen.
func (in *UpdateApplicationRequest) DeepCopy() *UpdateApplicationRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateApplicationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateApplicationRequest. Required by controller-gen.
func (in *UpdateApplicationRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateApplicationResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateApplicationResponse) DeepCopyInto(out *UpdateApplicationResponse) {
	p := proto.Clone(in).(*UpdateApplicationResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateApplicationResponse. Required by controller-gen.
func (in *UpdateApplicationResponse) DeepCopy() *UpdateApplicationResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateApplicationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateApplicationResponse. Required by controller-gen.
func (in *UpdateApplicationResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetAppDescriptionRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetAppDescriptionRequest) DeepCopyInto(out *GetAppDescriptionRequest) {
	p := proto.Clone(in).(*GetAppDescriptionRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAppDescriptionRequest. Required by controller-gen.
func (in *GetAppDescriptionRequest) DeepCopy() *GetAppDescriptionRequest {
	if in == nil {
		return nil
	}
	out := new(GetAppDescriptionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetAppDescriptionRequest. Required by controller-gen.
func (in *GetAppDescriptionRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetAppDescriptionResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetAppDescriptionResponse) DeepCopyInto(out *GetAppDescriptionResponse) {
	p := proto.Clone(in).(*GetAppDescriptionResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetAppDescriptionResponse. Required by controller-gen.
func (in *GetAppDescriptionResponse) DeepCopy() *GetAppDescriptionResponse {
	if in == nil {
		return nil
	}
	out := new(GetAppDescriptionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetAppDescriptionResponse. Required by controller-gen.
func (in *GetAppDescriptionResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateAppMasterRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateAppMasterRequest) DeepCopyInto(out *UpdateAppMasterRequest) {
	p := proto.Clone(in).(*UpdateAppMasterRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateAppMasterRequest. Required by controller-gen.
func (in *UpdateAppMasterRequest) DeepCopy() *UpdateAppMasterRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateAppMasterRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateAppMasterRequest. Required by controller-gen.
func (in *UpdateAppMasterRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateAppMasterResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateAppMasterResponse) DeepCopyInto(out *UpdateAppMasterResponse) {
	p := proto.Clone(in).(*UpdateAppMasterResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateAppMasterResponse. Required by controller-gen.
func (in *UpdateAppMasterResponse) DeepCopy() *UpdateAppMasterResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateAppMasterResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateAppMasterResponse. Required by controller-gen.
func (in *UpdateAppMasterResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateMasterOptionsRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateMasterOptionsRequest) DeepCopyInto(out *UpdateMasterOptionsRequest) {
	p := proto.Clone(in).(*UpdateMasterOptionsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMasterOptionsRequest. Required by controller-gen.
func (in *UpdateMasterOptionsRequest) DeepCopy() *UpdateMasterOptionsRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateMasterOptionsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMasterOptionsRequest. Required by controller-gen.
func (in *UpdateMasterOptionsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateMasterOptionsResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateMasterOptionsResponse) DeepCopyInto(out *UpdateMasterOptionsResponse) {
	p := proto.Clone(in).(*UpdateMasterOptionsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMasterOptionsResponse. Required by controller-gen.
func (in *UpdateMasterOptionsResponse) DeepCopy() *UpdateMasterOptionsResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateMasterOptionsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateMasterOptionsResponse. Required by controller-gen.
func (in *UpdateMasterOptionsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClearReserveSlotRequest within kubernetes types, where deepcopy-gen is used.
func (in *ClearReserveSlotRequest) DeepCopyInto(out *ClearReserveSlotRequest) {
	p := proto.Clone(in).(*ClearReserveSlotRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearReserveSlotRequest. Required by controller-gen.
func (in *ClearReserveSlotRequest) DeepCopy() *ClearReserveSlotRequest {
	if in == nil {
		return nil
	}
	out := new(ClearReserveSlotRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClearReserveSlotRequest. Required by controller-gen.
func (in *ClearReserveSlotRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClearReserveSlotResponse within kubernetes types, where deepcopy-gen is used.
func (in *ClearReserveSlotResponse) DeepCopyInto(out *ClearReserveSlotResponse) {
	p := proto.Clone(in).(*ClearReserveSlotResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearReserveSlotResponse. Required by controller-gen.
func (in *ClearReserveSlotResponse) DeepCopy() *ClearReserveSlotResponse {
	if in == nil {
		return nil
	}
	out := new(ClearReserveSlotResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClearReserveSlotResponse. Required by controller-gen.
func (in *ClearReserveSlotResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateResourceScoreTableRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateResourceScoreTableRequest) DeepCopyInto(out *UpdateResourceScoreTableRequest) {
	p := proto.Clone(in).(*UpdateResourceScoreTableRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourceScoreTableRequest. Required by controller-gen.
func (in *UpdateResourceScoreTableRequest) DeepCopy() *UpdateResourceScoreTableRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateResourceScoreTableRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourceScoreTableRequest. Required by controller-gen.
func (in *UpdateResourceScoreTableRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateResourceScoreTableResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateResourceScoreTableResponse) DeepCopyInto(out *UpdateResourceScoreTableResponse) {
	p := proto.Clone(in).(*UpdateResourceScoreTableResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourceScoreTableResponse. Required by controller-gen.
func (in *UpdateResourceScoreTableResponse) DeepCopy() *UpdateResourceScoreTableResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateResourceScoreTableResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateResourceScoreTableResponse. Required by controller-gen.
func (in *UpdateResourceScoreTableResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteResourceScoreTableRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteResourceScoreTableRequest) DeepCopyInto(out *DeleteResourceScoreTableRequest) {
	p := proto.Clone(in).(*DeleteResourceScoreTableRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteResourceScoreTableRequest. Required by controller-gen.
func (in *DeleteResourceScoreTableRequest) DeepCopy() *DeleteResourceScoreTableRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteResourceScoreTableRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteResourceScoreTableRequest. Required by controller-gen.
func (in *DeleteResourceScoreTableRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteResourceScoreTableResponse within kubernetes types, where deepcopy-gen is used.
func (in *DeleteResourceScoreTableResponse) DeepCopyInto(out *DeleteResourceScoreTableResponse) {
	p := proto.Clone(in).(*DeleteResourceScoreTableResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteResourceScoreTableResponse. Required by controller-gen.
func (in *DeleteResourceScoreTableResponse) DeepCopy() *DeleteResourceScoreTableResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteResourceScoreTableResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteResourceScoreTableResponse. Required by controller-gen.
func (in *DeleteResourceScoreTableResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListResourceScoreTableRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListResourceScoreTableRequest) DeepCopyInto(out *ListResourceScoreTableRequest) {
	p := proto.Clone(in).(*ListResourceScoreTableRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListResourceScoreTableRequest. Required by controller-gen.
func (in *ListResourceScoreTableRequest) DeepCopy() *ListResourceScoreTableRequest {
	if in == nil {
		return nil
	}
	out := new(ListResourceScoreTableRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListResourceScoreTableRequest. Required by controller-gen.
func (in *ListResourceScoreTableRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListResourceScoreTableResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListResourceScoreTableResponse) DeepCopyInto(out *ListResourceScoreTableResponse) {
	p := proto.Clone(in).(*ListResourceScoreTableResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListResourceScoreTableResponse. Required by controller-gen.
func (in *ListResourceScoreTableResponse) DeepCopy() *ListResourceScoreTableResponse {
	if in == nil {
		return nil
	}
	out := new(ListResourceScoreTableResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListResourceScoreTableResponse. Required by controller-gen.
func (in *ListResourceScoreTableResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateConfigsRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateConfigsRequest) DeepCopyInto(out *UpdateConfigsRequest) {
	p := proto.Clone(in).(*UpdateConfigsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateConfigsRequest. Required by controller-gen.
func (in *UpdateConfigsRequest) DeepCopy() *UpdateConfigsRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateConfigsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateConfigsRequest. Required by controller-gen.
func (in *UpdateConfigsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateConfigsResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateConfigsResponse) DeepCopyInto(out *UpdateConfigsResponse) {
	p := proto.Clone(in).(*UpdateConfigsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateConfigsResponse. Required by controller-gen.
func (in *UpdateConfigsResponse) DeepCopy() *UpdateConfigsResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateConfigsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateConfigsResponse. Required by controller-gen.
func (in *UpdateConfigsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetConfigsRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetConfigsRequest) DeepCopyInto(out *GetConfigsRequest) {
	p := proto.Clone(in).(*GetConfigsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetConfigsRequest. Required by controller-gen.
func (in *GetConfigsRequest) DeepCopy() *GetConfigsRequest {
	if in == nil {
		return nil
	}
	out := new(GetConfigsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetConfigsRequest. Required by controller-gen.
func (in *GetConfigsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetConfigsResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetConfigsResponse) DeepCopyInto(out *GetConfigsResponse) {
	p := proto.Clone(in).(*GetConfigsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetConfigsResponse. Required by controller-gen.
func (in *GetConfigsResponse) DeepCopy() *GetConfigsResponse {
	if in == nil {
		return nil
	}
	out := new(GetConfigsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetConfigsResponse. Required by controller-gen.
func (in *GetConfigsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelConfigsRequest within kubernetes types, where deepcopy-gen is used.
func (in *DelConfigsRequest) DeepCopyInto(out *DelConfigsRequest) {
	p := proto.Clone(in).(*DelConfigsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelConfigsRequest. Required by controller-gen.
func (in *DelConfigsRequest) DeepCopy() *DelConfigsRequest {
	if in == nil {
		return nil
	}
	out := new(DelConfigsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelConfigsRequest. Required by controller-gen.
func (in *DelConfigsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DelConfigsResponse within kubernetes types, where deepcopy-gen is used.
func (in *DelConfigsResponse) DeepCopyInto(out *DelConfigsResponse) {
	p := proto.Clone(in).(*DelConfigsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DelConfigsResponse. Required by controller-gen.
func (in *DelConfigsResponse) DeepCopy() *DelConfigsResponse {
	if in == nil {
		return nil
	}
	out := new(DelConfigsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DelConfigsResponse. Required by controller-gen.
func (in *DelConfigsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetReserveSlotsRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetReserveSlotsRequest) DeepCopyInto(out *GetReserveSlotsRequest) {
	p := proto.Clone(in).(*GetReserveSlotsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetReserveSlotsRequest. Required by controller-gen.
func (in *GetReserveSlotsRequest) DeepCopy() *GetReserveSlotsRequest {
	if in == nil {
		return nil
	}
	out := new(GetReserveSlotsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetReserveSlotsRequest. Required by controller-gen.
func (in *GetReserveSlotsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetReserveSlotsResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetReserveSlotsResponse) DeepCopyInto(out *GetReserveSlotsResponse) {
	p := proto.Clone(in).(*GetReserveSlotsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetReserveSlotsResponse. Required by controller-gen.
func (in *GetReserveSlotsResponse) DeepCopy() *GetReserveSlotsResponse {
	if in == nil {
		return nil
	}
	out := new(GetReserveSlotsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetReserveSlotsResponse. Required by controller-gen.
func (in *GetReserveSlotsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClearReserveSlotsRequest within kubernetes types, where deepcopy-gen is used.
func (in *ClearReserveSlotsRequest) DeepCopyInto(out *ClearReserveSlotsRequest) {
	p := proto.Clone(in).(*ClearReserveSlotsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearReserveSlotsRequest. Required by controller-gen.
func (in *ClearReserveSlotsRequest) DeepCopy() *ClearReserveSlotsRequest {
	if in == nil {
		return nil
	}
	out := new(ClearReserveSlotsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClearReserveSlotsRequest. Required by controller-gen.
func (in *ClearReserveSlotsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ClearReserveSlotsResponse within kubernetes types, where deepcopy-gen is used.
func (in *ClearReserveSlotsResponse) DeepCopyInto(out *ClearReserveSlotsResponse) {
	p := proto.Clone(in).(*ClearReserveSlotsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClearReserveSlotsResponse. Required by controller-gen.
func (in *ClearReserveSlotsResponse) DeepCopy() *ClearReserveSlotsResponse {
	if in == nil {
		return nil
	}
	out := new(ClearReserveSlotsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ClearReserveSlotsResponse. Required by controller-gen.
func (in *ClearReserveSlotsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetRawRequestsRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetRawRequestsRequest) DeepCopyInto(out *GetRawRequestsRequest) {
	p := proto.Clone(in).(*GetRawRequestsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRawRequestsRequest. Required by controller-gen.
func (in *GetRawRequestsRequest) DeepCopy() *GetRawRequestsRequest {
	if in == nil {
		return nil
	}
	out := new(GetRawRequestsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetRawRequestsRequest. Required by controller-gen.
func (in *GetRawRequestsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetRawRequestsResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetRawRequestsResponse) DeepCopyInto(out *GetRawRequestsResponse) {
	p := proto.Clone(in).(*GetRawRequestsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRawRequestsResponse. Required by controller-gen.
func (in *GetRawRequestsResponse) DeepCopy() *GetRawRequestsResponse {
	if in == nil {
		return nil
	}
	out := new(GetRawRequestsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetRawRequestsResponse. Required by controller-gen.
func (in *GetRawRequestsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using BufferRuleRequire within kubernetes types, where deepcopy-gen is used.
func (in *BufferRuleRequire) DeepCopyInto(out *BufferRuleRequire) {
	p := proto.Clone(in).(*BufferRuleRequire)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BufferRuleRequire. Required by controller-gen.
func (in *BufferRuleRequire) DeepCopy() *BufferRuleRequire {
	if in == nil {
		return nil
	}
	out := new(BufferRuleRequire)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new BufferRuleRequire. Required by controller-gen.
func (in *BufferRuleRequire) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using FieldInfo within kubernetes types, where deepcopy-gen is used.
func (in *FieldInfo) DeepCopyInto(out *FieldInfo) {
	p := proto.Clone(in).(*FieldInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldInfo. Required by controller-gen.
func (in *FieldInfo) DeepCopy() *FieldInfo {
	if in == nil {
		return nil
	}
	out := new(FieldInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new FieldInfo. Required by controller-gen.
func (in *FieldInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using BufferRule within kubernetes types, where deepcopy-gen is used.
func (in *BufferRule) DeepCopyInto(out *BufferRule) {
	p := proto.Clone(in).(*BufferRule)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BufferRule. Required by controller-gen.
func (in *BufferRule) DeepCopy() *BufferRule {
	if in == nil {
		return nil
	}
	out := new(BufferRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new BufferRule. Required by controller-gen.
func (in *BufferRule) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddBufferRuleRequest within kubernetes types, where deepcopy-gen is used.
func (in *AddBufferRuleRequest) DeepCopyInto(out *AddBufferRuleRequest) {
	p := proto.Clone(in).(*AddBufferRuleRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddBufferRuleRequest. Required by controller-gen.
func (in *AddBufferRuleRequest) DeepCopy() *AddBufferRuleRequest {
	if in == nil {
		return nil
	}
	out := new(AddBufferRuleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddBufferRuleRequest. Required by controller-gen.
func (in *AddBufferRuleRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using AddBufferRuleResponse within kubernetes types, where deepcopy-gen is used.
func (in *AddBufferRuleResponse) DeepCopyInto(out *AddBufferRuleResponse) {
	p := proto.Clone(in).(*AddBufferRuleResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddBufferRuleResponse. Required by controller-gen.
func (in *AddBufferRuleResponse) DeepCopy() *AddBufferRuleResponse {
	if in == nil {
		return nil
	}
	out := new(AddBufferRuleResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new AddBufferRuleResponse. Required by controller-gen.
func (in *AddBufferRuleResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateBufferRuleInfo within kubernetes types, where deepcopy-gen is used.
func (in *UpdateBufferRuleInfo) DeepCopyInto(out *UpdateBufferRuleInfo) {
	p := proto.Clone(in).(*UpdateBufferRuleInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateBufferRuleInfo. Required by controller-gen.
func (in *UpdateBufferRuleInfo) DeepCopy() *UpdateBufferRuleInfo {
	if in == nil {
		return nil
	}
	out := new(UpdateBufferRuleInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateBufferRuleInfo. Required by controller-gen.
func (in *UpdateBufferRuleInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateBufferRuleRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateBufferRuleRequest) DeepCopyInto(out *UpdateBufferRuleRequest) {
	p := proto.Clone(in).(*UpdateBufferRuleRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateBufferRuleRequest. Required by controller-gen.
func (in *UpdateBufferRuleRequest) DeepCopy() *UpdateBufferRuleRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateBufferRuleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateBufferRuleRequest. Required by controller-gen.
func (in *UpdateBufferRuleRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateBufferRuleResponse within kubernetes types, where deepcopy-gen is used.
func (in *UpdateBufferRuleResponse) DeepCopyInto(out *UpdateBufferRuleResponse) {
	p := proto.Clone(in).(*UpdateBufferRuleResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateBufferRuleResponse. Required by controller-gen.
func (in *UpdateBufferRuleResponse) DeepCopy() *UpdateBufferRuleResponse {
	if in == nil {
		return nil
	}
	out := new(UpdateBufferRuleResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateBufferRuleResponse. Required by controller-gen.
func (in *UpdateBufferRuleResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteBufferRuleRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteBufferRuleRequest) DeepCopyInto(out *DeleteBufferRuleRequest) {
	p := proto.Clone(in).(*DeleteBufferRuleRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteBufferRuleRequest. Required by controller-gen.
func (in *DeleteBufferRuleRequest) DeepCopy() *DeleteBufferRuleRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteBufferRuleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteBufferRuleRequest. Required by controller-gen.
func (in *DeleteBufferRuleRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteBufferRuleResponse within kubernetes types, where deepcopy-gen is used.
func (in *DeleteBufferRuleResponse) DeepCopyInto(out *DeleteBufferRuleResponse) {
	p := proto.Clone(in).(*DeleteBufferRuleResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteBufferRuleResponse. Required by controller-gen.
func (in *DeleteBufferRuleResponse) DeepCopy() *DeleteBufferRuleResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteBufferRuleResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteBufferRuleResponse. Required by controller-gen.
func (in *DeleteBufferRuleResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ReserveInfo within kubernetes types, where deepcopy-gen is used.
func (in *ReserveInfo) DeepCopyInto(out *ReserveInfo) {
	p := proto.Clone(in).(*ReserveInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReserveInfo. Required by controller-gen.
func (in *ReserveInfo) DeepCopy() *ReserveInfo {
	if in == nil {
		return nil
	}
	out := new(ReserveInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ReserveInfo. Required by controller-gen.
func (in *ReserveInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using BufferRuleInfo within kubernetes types, where deepcopy-gen is used.
func (in *BufferRuleInfo) DeepCopyInto(out *BufferRuleInfo) {
	p := proto.Clone(in).(*BufferRuleInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BufferRuleInfo. Required by controller-gen.
func (in *BufferRuleInfo) DeepCopy() *BufferRuleInfo {
	if in == nil {
		return nil
	}
	out := new(BufferRuleInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new BufferRuleInfo. Required by controller-gen.
func (in *BufferRuleInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetBufferRuleRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetBufferRuleRequest) DeepCopyInto(out *GetBufferRuleRequest) {
	p := proto.Clone(in).(*GetBufferRuleRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetBufferRuleRequest. Required by controller-gen.
func (in *GetBufferRuleRequest) DeepCopy() *GetBufferRuleRequest {
	if in == nil {
		return nil
	}
	out := new(GetBufferRuleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetBufferRuleRequest. Required by controller-gen.
func (in *GetBufferRuleRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetBufferRuleResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetBufferRuleResponse) DeepCopyInto(out *GetBufferRuleResponse) {
	p := proto.Clone(in).(*GetBufferRuleResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetBufferRuleResponse. Required by controller-gen.
func (in *GetBufferRuleResponse) DeepCopy() *GetBufferRuleResponse {
	if in == nil {
		return nil
	}
	out := new(GetBufferRuleResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetBufferRuleResponse. Required by controller-gen.
func (in *GetBufferRuleResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ReleaseBufferRuleSlotsRequest within kubernetes types, where deepcopy-gen is used.
func (in *ReleaseBufferRuleSlotsRequest) DeepCopyInto(out *ReleaseBufferRuleSlotsRequest) {
	p := proto.Clone(in).(*ReleaseBufferRuleSlotsRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseBufferRuleSlotsRequest. Required by controller-gen.
func (in *ReleaseBufferRuleSlotsRequest) DeepCopy() *ReleaseBufferRuleSlotsRequest {
	if in == nil {
		return nil
	}
	out := new(ReleaseBufferRuleSlotsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseBufferRuleSlotsRequest. Required by controller-gen.
func (in *ReleaseBufferRuleSlotsRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ReleaseBufferRuleSlotsResponse within kubernetes types, where deepcopy-gen is used.
func (in *ReleaseBufferRuleSlotsResponse) DeepCopyInto(out *ReleaseBufferRuleSlotsResponse) {
	p := proto.Clone(in).(*ReleaseBufferRuleSlotsResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseBufferRuleSlotsResponse. Required by controller-gen.
func (in *ReleaseBufferRuleSlotsResponse) DeepCopy() *ReleaseBufferRuleSlotsResponse {
	if in == nil {
		return nil
	}
	out := new(ReleaseBufferRuleSlotsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseBufferRuleSlotsResponse. Required by controller-gen.
func (in *ReleaseBufferRuleSlotsResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetClusterInfoRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetClusterInfoRequest) DeepCopyInto(out *GetClusterInfoRequest) {
	p := proto.Clone(in).(*GetClusterInfoRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetClusterInfoRequest. Required by controller-gen.
func (in *GetClusterInfoRequest) DeepCopy() *GetClusterInfoRequest {
	if in == nil {
		return nil
	}
	out := new(GetClusterInfoRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetClusterInfoRequest. Required by controller-gen.
func (in *GetClusterInfoRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetClusterInfoResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetClusterInfoResponse) DeepCopyInto(out *GetClusterInfoResponse) {
	p := proto.Clone(in).(*GetClusterInfoResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetClusterInfoResponse. Required by controller-gen.
func (in *GetClusterInfoResponse) DeepCopy() *GetClusterInfoResponse {
	if in == nil {
		return nil
	}
	out := new(GetClusterInfoResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetClusterInfoResponse. Required by controller-gen.
func (in *GetClusterInfoResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NullRequest within kubernetes types, where deepcopy-gen is used.
func (in *NullRequest) DeepCopyInto(out *NullRequest) {
	p := proto.Clone(in).(*NullRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NullRequest. Required by controller-gen.
func (in *NullRequest) DeepCopy() *NullRequest {
	if in == nil {
		return nil
	}
	out := new(NullRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NullRequest. Required by controller-gen.
func (in *NullRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GangRegion within kubernetes types, where deepcopy-gen is used.
func (in *GangRegion) DeepCopyInto(out *GangRegion) {
	p := proto.Clone(in).(*GangRegion)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GangRegion. Required by controller-gen.
func (in *GangRegion) DeepCopy() *GangRegion {
	if in == nil {
		return nil
	}
	out := new(GangRegion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GangRegion. Required by controller-gen.
func (in *GangRegion) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GangInfo within kubernetes types, where deepcopy-gen is used.
func (in *GangInfo) DeepCopyInto(out *GangInfo) {
	p := proto.Clone(in).(*GangInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GangInfo. Required by controller-gen.
func (in *GangInfo) DeepCopy() *GangInfo {
	if in == nil {
		return nil
	}
	out := new(GangInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GangInfo. Required by controller-gen.
func (in *GangInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetGangInfoRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetGangInfoRequest) DeepCopyInto(out *GetGangInfoRequest) {
	p := proto.Clone(in).(*GetGangInfoRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetGangInfoRequest. Required by controller-gen.
func (in *GetGangInfoRequest) DeepCopy() *GetGangInfoRequest {
	if in == nil {
		return nil
	}
	out := new(GetGangInfoRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetGangInfoRequest. Required by controller-gen.
func (in *GetGangInfoRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GetGangInfoResponse within kubernetes types, where deepcopy-gen is used.
func (in *GetGangInfoResponse) DeepCopyInto(out *GetGangInfoResponse) {
	p := proto.Clone(in).(*GetGangInfoResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetGangInfoResponse. Required by controller-gen.
func (in *GetGangInfoResponse) DeepCopy() *GetGangInfoResponse {
	if in == nil {
		return nil
	}
	out := new(GetGangInfoResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetGangInfoResponse. Required by controller-gen.
func (in *GetGangInfoResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
