/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// CarbonJobListerExpansion allows custom methods to be added to
// CarbonJobLister.
type CarbonJobListerExpansion interface{}

// CarbonJobNamespaceListerExpansion allows custom methods to be added to
// CarbonJobNamespaceLister.
type CarbonJobNamespaceListerExpansion interface{}

// RollingSetListerExpansion allows custom methods to be added to
// RollingSetLister.
type RollingSetListerExpansion interface{}

// RollingSetNamespaceListerExpansion allows custom methods to be added to
// RollingSetNamespaceLister.
type RollingSetNamespaceListerExpansion interface{}

// ServicePublisherListerExpansion allows custom methods to be added to
// ServicePublisherLister.
type ServicePublisherListerExpansion interface{}

// ServicePublisherNamespaceListerExpansion allows custom methods to be added to
// ServicePublisherNamespaceLister.
type ServicePublisherNamespaceListerExpansion interface{}

// ShardGroupListerExpansion allows custom methods to be added to
// ShardGroupLister.
type ShardGroupListerExpansion interface{}

// ShardGroupNamespaceListerExpansion allows custom methods to be added to
// ShardGroupNamespaceLister.
type ShardGroupNamespaceListerExpansion interface{}

// TemporaryConstraintListerExpansion allows custom methods to be added to
// TemporaryConstraintLister.
type TemporaryConstraintListerExpansion interface{}

// TemporaryConstraintNamespaceListerExpansion allows custom methods to be added to
// TemporaryConstraintNamespaceLister.
type TemporaryConstraintNamespaceListerExpansion interface{}

// WorkerNodeListerExpansion allows custom methods to be added to
// WorkerNodeLister.
type WorkerNodeListerExpansion interface{}

// WorkerNodeNamespaceListerExpansion allows custom methods to be added to
// WorkerNodeNamespaceLister.
type WorkerNodeNamespaceListerExpansion interface{}

// WorkerNodeEvictionListerExpansion allows custom methods to be added to
// WorkerNodeEvictionLister.
type WorkerNodeEvictionListerExpansion interface{}

// WorkerNodeEvictionNamespaceListerExpansion allows custom methods to be added to
// WorkerNodeEvictionNamespaceLister.
type WorkerNodeEvictionNamespaceListerExpansion interface{}
