/*
Copyright 2024 The Alibaba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package compatible

import (
	"github.com/alibaba/kube-sharding/pkg/apiserver-client/typespec/carbon"
	"github.com/alibaba/kube-sharding/pkg/apiserver-client/typespec/hippo"
)

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlotInfo.
func (in *SlotInfo) DeepCopy() *SlotInfo {
	if in == nil {
		return nil
	}
	out := new(SlotInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlotInfo) DeepCopyInto(out *SlotInfo) {
	*out = *in
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(string)
		**out = **in
	}
	in.SlotID.DeepCopyInto(&out.SlotID)
	if in.SlotResource != nil {
		in, out := &in.SlotResource, &out.SlotResource
		*out = new(carbon.SlotResource)
		(*in).DeepCopyInto(*out)
	}
	if in.SlaveStatus != nil {
		in, out := &in.SlaveStatus, &out.SlaveStatus
		*out = new(hippo.SlaveStatus_Status)
		**out = **in
	}
	if in.ProcessStatus != nil {
		in, out := &in.ProcessStatus, &out.ProcessStatus
		*out = new([]*hippo.ProcessStatus)
		if **in != nil {
			in, out := *in, *out
			*out = make([]*hippo.ProcessStatus, len(*in))
			for i := range *in {
				if (*in)[i] != nil {
					in, out := &(*in)[i], &(*out)[i]
					*out = new(hippo.ProcessStatus)
					(*in).DeepCopyInto(*out)
				}
			}
		}
	}
	if in.PackageStatus != nil {
		in, out := &in.PackageStatus, &out.PackageStatus
		*out = new(hippo.PackageStatus_Status)
		**out = **in
	}
	if in.PreDeployPackageStatus != nil {
		in, out := &in.PreDeployPackageStatus, &out.PreDeployPackageStatus
		*out = new(hippo.PackageStatus_Status)
		**out = **in
	}
	if in.PackageChecksum != nil {
		in, out := &in.PackageChecksum, &out.PackageChecksum
		*out = new(string)
		**out = **in
	}
	if in.PreDeployPackageChecksum != nil {
		in, out := &in.PreDeployPackageChecksum, &out.PreDeployPackageChecksum
		*out = new(string)
		**out = **in
	}
	if in.LaunchSignature != nil {
		in, out := &in.LaunchSignature, &out.LaunchSignature
		*out = new(int64)
		**out = **in
	}
	if in.NoLongerMatchQueue != nil {
		in, out := &in.NoLongerMatchQueue, &out.NoLongerMatchQueue
		*out = new(bool)
		**out = **in
	}
	if in.NoLongerMatchResourceRequirement != nil {
		in, out := &in.NoLongerMatchResourceRequirement, &out.NoLongerMatchResourceRequirement
		*out = new(bool)
		**out = **in
	}
	return
}
