/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	carbonv1 "github.com/alibaba/kube-sharding/pkg/apis/carbon/v1"
	versioned "github.com/alibaba/kube-sharding/pkg/client/clientset/versioned"
	internalinterfaces "github.com/alibaba/kube-sharding/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/alibaba/kube-sharding/pkg/client/listers/carbon/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RollingSetInformer provides access to a shared informer and lister for
// RollingSets.
type RollingSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.RollingSetLister
}

type rollingSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRollingSetInformer constructs a new informer for RollingSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRollingSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRollingSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRollingSetInformer constructs a new informer for RollingSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRollingSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CarbonV1().RollingSets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CarbonV1().RollingSets(namespace).Watch(context.TODO(), options)
			},
		},
		&carbonv1.RollingSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *rollingSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRollingSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rollingSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&carbonv1.RollingSet{}, f.defaultInformer)
}

func (f *rollingSetInformer) Lister() v1.RollingSetLister {
	return v1.NewRollingSetLister(f.Informer().GetIndexer())
}
