/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	carbonv1 "github.com/alibaba/kube-sharding/pkg/apis/carbon/v1"
	versioned "github.com/alibaba/kube-sharding/pkg/client/clientset/versioned"
	internalinterfaces "github.com/alibaba/kube-sharding/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/alibaba/kube-sharding/pkg/client/listers/carbon/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TemporaryConstraintInformer provides access to a shared informer and lister for
// TemporaryConstraints.
type TemporaryConstraintInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.TemporaryConstraintLister
}

type temporaryConstraintInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTemporaryConstraintInformer constructs a new informer for TemporaryConstraint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTemporaryConstraintInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTemporaryConstraintInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTemporaryConstraintInformer constructs a new informer for TemporaryConstraint type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTemporaryConstraintInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CarbonV1().TemporaryConstraints(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CarbonV1().TemporaryConstraints(namespace).Watch(context.TODO(), options)
			},
		},
		&carbonv1.TemporaryConstraint{},
		resyncPeriod,
		indexers,
	)
}

func (f *temporaryConstraintInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTemporaryConstraintInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *temporaryConstraintInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&carbonv1.TemporaryConstraint{}, f.defaultInformer)
}

func (f *temporaryConstraintInformer) Lister() v1.TemporaryConstraintLister {
	return v1.NewTemporaryConstraintLister(f.Informer().GetIndexer())
}
