/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	carbonv1 "github.com/alibaba/kube-sharding/pkg/apis/carbon/v1"
	versioned "github.com/alibaba/kube-sharding/pkg/client/clientset/versioned"
	internalinterfaces "github.com/alibaba/kube-sharding/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/alibaba/kube-sharding/pkg/client/listers/carbon/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// WorkerNodeEvictionInformer provides access to a shared informer and lister for
// WorkerNodeEvictions.
type WorkerNodeEvictionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.WorkerNodeEvictionLister
}

type workerNodeEvictionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWorkerNodeEvictionInformer constructs a new informer for WorkerNodeEviction type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWorkerNodeEvictionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWorkerNodeEvictionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWorkerNodeEvictionInformer constructs a new informer for WorkerNodeEviction type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWorkerNodeEvictionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CarbonV1().WorkerNodeEvictions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CarbonV1().WorkerNodeEvictions(namespace).Watch(context.TODO(), options)
			},
		},
		&carbonv1.WorkerNodeEviction{},
		resyncPeriod,
		indexers,
	)
}

func (f *workerNodeEvictionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWorkerNodeEvictionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *workerNodeEvictionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&carbonv1.WorkerNodeEviction{}, f.defaultInformer)
}

func (f *workerNodeEvictionInformer) Lister() v1.WorkerNodeEvictionLister {
	return v1.NewWorkerNodeEvictionLister(f.Informer().GetIndexer())
}
