// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: carbon/Status.proto

package carbon

import (
	fmt "fmt"

	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using HealthInfo within kubernetes types, where deepcopy-gen is used.
func (in *HealthInfo) DeepCopyInto(out *HealthInfo) {
	p := proto.Clone(in).(*HealthInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthInfo. Required by controller-gen.
func (in *HealthInfo) DeepCopy() *HealthInfo {
	if in == nil {
		return nil
	}
	out := new(HealthInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new HealthInfo. Required by controller-gen.
func (in *HealthInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ServiceStatus within kubernetes types, where deepcopy-gen is used.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	p := proto.Clone(in).(*ServiceStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus. Required by controller-gen.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus. Required by controller-gen.
func (in *ServiceStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlotStatus within kubernetes types, where deepcopy-gen is used.
func (in *SlotStatus) DeepCopyInto(out *SlotStatus) {
	p := proto.Clone(in).(*SlotStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlotStatus. Required by controller-gen.
func (in *SlotStatus) DeepCopy() *SlotStatus {
	if in == nil {
		return nil
	}
	out := new(SlotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlotStatus. Required by controller-gen.
func (in *SlotStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlotInfo within kubernetes types, where deepcopy-gen is used.
func (in *SlotInfo) DeepCopyInto(out *SlotInfo) {
	p := proto.Clone(in).(*SlotInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlotInfo. Required by controller-gen.
func (in *SlotInfo) DeepCopy() *SlotInfo {
	if in == nil {
		return nil
	}
	out := new(SlotInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlotInfo. Required by controller-gen.
func (in *SlotInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using WorkerNodeStatus within kubernetes types, where deepcopy-gen is used.
func (in *WorkerNodeStatus) DeepCopyInto(out *WorkerNodeStatus) {
	p := proto.Clone(in).(*WorkerNodeStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerNodeStatus. Required by controller-gen.
func (in *WorkerNodeStatus) DeepCopy() *WorkerNodeStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new WorkerNodeStatus. Required by controller-gen.
func (in *WorkerNodeStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ReplicaNodeStatus within kubernetes types, where deepcopy-gen is used.
func (in *ReplicaNodeStatus) DeepCopyInto(out *ReplicaNodeStatus) {
	p := proto.Clone(in).(*ReplicaNodeStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaNodeStatus. Required by controller-gen.
func (in *ReplicaNodeStatus) DeepCopy() *ReplicaNodeStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicaNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaNodeStatus. Required by controller-gen.
func (in *ReplicaNodeStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GlobalPlan within kubernetes types, where deepcopy-gen is used.
func (in *GlobalPlan) DeepCopyInto(out *GlobalPlan) {
	p := proto.Clone(in).(*GlobalPlan)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalPlan. Required by controller-gen.
func (in *GlobalPlan) DeepCopy() *GlobalPlan {
	if in == nil {
		return nil
	}
	out := new(GlobalPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GlobalPlan. Required by controller-gen.
func (in *GlobalPlan) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RoleStatusValue within kubernetes types, where deepcopy-gen is used.
func (in *RoleStatusValue) DeepCopyInto(out *RoleStatusValue) {
	p := proto.Clone(in).(*RoleStatusValue)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleStatusValue. Required by controller-gen.
func (in *RoleStatusValue) DeepCopy() *RoleStatusValue {
	if in == nil {
		return nil
	}
	out := new(RoleStatusValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RoleStatusValue. Required by controller-gen.
func (in *RoleStatusValue) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GroupStatus within kubernetes types, where deepcopy-gen is used.
func (in *GroupStatus) DeepCopyInto(out *GroupStatus) {
	p := proto.Clone(in).(*GroupStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatus. Required by controller-gen.
func (in *GroupStatus) DeepCopy() *GroupStatus {
	if in == nil {
		return nil
	}
	out := new(GroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatus. Required by controller-gen.
func (in *GroupStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Response within kubernetes types, where deepcopy-gen is used.
func (in *Response) DeepCopyInto(out *Response) {
	p := proto.Clone(in).(*Response)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Response. Required by controller-gen.
func (in *Response) DeepCopy() *Response {
	if in == nil {
		return nil
	}
	out := new(Response)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Response. Required by controller-gen.
func (in *Response) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CarbonPriority within kubernetes types, where deepcopy-gen is used.
func (in *CarbonPriority) DeepCopyInto(out *CarbonPriority) {
	p := proto.Clone(in).(*CarbonPriority)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarbonPriority. Required by controller-gen.
func (in *CarbonPriority) DeepCopy() *CarbonPriority {
	if in == nil {
		return nil
	}
	out := new(CarbonPriority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CarbonPriority. Required by controller-gen.
func (in *CarbonPriority) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SlotResource within kubernetes types, where deepcopy-gen is used.
func (in *SlotResource) DeepCopyInto(out *SlotResource) {
	p := proto.Clone(in).(*SlotResource)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlotResource. Required by controller-gen.
func (in *SlotResource) DeepCopy() *SlotResource {
	if in == nil {
		return nil
	}
	out := new(SlotResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SlotResource. Required by controller-gen.
func (in *SlotResource) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourcePlan within kubernetes types, where deepcopy-gen is used.
func (in *ResourcePlan) DeepCopyInto(out *ResourcePlan) {
	p := proto.Clone(in).(*ResourcePlan)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePlan. Required by controller-gen.
func (in *ResourcePlan) DeepCopy() *ResourcePlan {
	if in == nil {
		return nil
	}
	out := new(ResourcePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePlan. Required by controller-gen.
func (in *ResourcePlan) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using VersionedPlan within kubernetes types, where deepcopy-gen is used.
func (in *VersionedPlan) DeepCopyInto(out *VersionedPlan) {
	p := proto.Clone(in).(*VersionedPlan)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionedPlan. Required by controller-gen.
func (in *VersionedPlan) DeepCopy() *VersionedPlan {
	if in == nil {
		return nil
	}
	out := new(VersionedPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VersionedPlan. Required by controller-gen.
func (in *VersionedPlan) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
