/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	carbonv1 "github.com/alibaba/kube-sharding/pkg/apis/carbon/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkerNodes implements WorkerNodeInterface
type FakeWorkerNodes struct {
	Fake *FakeCarbonV1
	ns   string
}

var workernodesResource = schema.GroupVersionResource{Group: "carbon.taobao.com", Version: "v1", Resource: "workernodes"}

var workernodesKind = schema.GroupVersionKind{Group: "carbon.taobao.com", Version: "v1", Kind: "WorkerNode"}

// Get takes name of the workerNode, and returns the corresponding workerNode object, and an error if there is any.
func (c *FakeWorkerNodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *carbonv1.WorkerNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(workernodesResource, c.ns, name), &carbonv1.WorkerNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.WorkerNode), err
}

// List takes label and field selectors, and returns the list of WorkerNodes that match those selectors.
func (c *FakeWorkerNodes) List(ctx context.Context, opts v1.ListOptions) (result *carbonv1.WorkerNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(workernodesResource, workernodesKind, c.ns, opts), &carbonv1.WorkerNodeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &carbonv1.WorkerNodeList{ListMeta: obj.(*carbonv1.WorkerNodeList).ListMeta}
	for _, item := range obj.(*carbonv1.WorkerNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workerNodes.
func (c *FakeWorkerNodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(workernodesResource, c.ns, opts))

}

// Create takes the representation of a workerNode and creates it.  Returns the server's representation of the workerNode, and an error, if there is any.
func (c *FakeWorkerNodes) Create(ctx context.Context, workerNode *carbonv1.WorkerNode, opts v1.CreateOptions) (result *carbonv1.WorkerNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(workernodesResource, c.ns, workerNode), &carbonv1.WorkerNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.WorkerNode), err
}

// Update takes the representation of a workerNode and updates it. Returns the server's representation of the workerNode, and an error, if there is any.
func (c *FakeWorkerNodes) Update(ctx context.Context, workerNode *carbonv1.WorkerNode, opts v1.UpdateOptions) (result *carbonv1.WorkerNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(workernodesResource, c.ns, workerNode), &carbonv1.WorkerNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.WorkerNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkerNodes) UpdateStatus(ctx context.Context, workerNode *carbonv1.WorkerNode, opts v1.UpdateOptions) (*carbonv1.WorkerNode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(workernodesResource, "status", c.ns, workerNode), &carbonv1.WorkerNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.WorkerNode), err
}

// Delete takes name of the workerNode and deletes it. Returns an error if one occurs.
func (c *FakeWorkerNodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(workernodesResource, c.ns, name), &carbonv1.WorkerNode{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkerNodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(workernodesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &carbonv1.WorkerNodeList{})
	return err
}

// Patch applies the patch and returns the patched workerNode.
func (c *FakeWorkerNodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *carbonv1.WorkerNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workernodesResource, c.ns, name, pt, data, subresources...), &carbonv1.WorkerNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.WorkerNode), err
}
