/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	carbonv1 "github.com/alibaba/kube-sharding/pkg/apis/carbon/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkerNodeEvictions implements WorkerNodeEvictionInterface
type FakeWorkerNodeEvictions struct {
	Fake *FakeCarbonV1
	ns   string
}

var workernodeevictionsResource = schema.GroupVersionResource{Group: "carbon.taobao.com", Version: "v1", Resource: "workernodeevictions"}

var workernodeevictionsKind = schema.GroupVersionKind{Group: "carbon.taobao.com", Version: "v1", Kind: "WorkerNodeEviction"}

// Get takes name of the workerNodeEviction, and returns the corresponding workerNodeEviction object, and an error if there is any.
func (c *FakeWorkerNodeEvictions) Get(ctx context.Context, name string, options v1.GetOptions) (result *carbonv1.WorkerNodeEviction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(workernodeevictionsResource, c.ns, name), &carbonv1.WorkerNodeEviction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.WorkerNodeEviction), err
}

// List takes label and field selectors, and returns the list of WorkerNodeEvictions that match those selectors.
func (c *FakeWorkerNodeEvictions) List(ctx context.Context, opts v1.ListOptions) (result *carbonv1.WorkerNodeEvictionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(workernodeevictionsResource, workernodeevictionsKind, c.ns, opts), &carbonv1.WorkerNodeEvictionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &carbonv1.WorkerNodeEvictionList{ListMeta: obj.(*carbonv1.WorkerNodeEvictionList).ListMeta}
	for _, item := range obj.(*carbonv1.WorkerNodeEvictionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workerNodeEvictions.
func (c *FakeWorkerNodeEvictions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(workernodeevictionsResource, c.ns, opts))

}

// Create takes the representation of a workerNodeEviction and creates it.  Returns the server's representation of the workerNodeEviction, and an error, if there is any.
func (c *FakeWorkerNodeEvictions) Create(ctx context.Context, workerNodeEviction *carbonv1.WorkerNodeEviction, opts v1.CreateOptions) (result *carbonv1.WorkerNodeEviction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(workernodeevictionsResource, c.ns, workerNodeEviction), &carbonv1.WorkerNodeEviction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.WorkerNodeEviction), err
}

// Update takes the representation of a workerNodeEviction and updates it. Returns the server's representation of the workerNodeEviction, and an error, if there is any.
func (c *FakeWorkerNodeEvictions) Update(ctx context.Context, workerNodeEviction *carbonv1.WorkerNodeEviction, opts v1.UpdateOptions) (result *carbonv1.WorkerNodeEviction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(workernodeevictionsResource, c.ns, workerNodeEviction), &carbonv1.WorkerNodeEviction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.WorkerNodeEviction), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkerNodeEvictions) UpdateStatus(ctx context.Context, workerNodeEviction *carbonv1.WorkerNodeEviction, opts v1.UpdateOptions) (*carbonv1.WorkerNodeEviction, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(workernodeevictionsResource, "status", c.ns, workerNodeEviction), &carbonv1.WorkerNodeEviction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.WorkerNodeEviction), err
}

// Delete takes name of the workerNodeEviction and deletes it. Returns an error if one occurs.
func (c *FakeWorkerNodeEvictions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(workernodeevictionsResource, c.ns, name), &carbonv1.WorkerNodeEviction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkerNodeEvictions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(workernodeevictionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &carbonv1.WorkerNodeEvictionList{})
	return err
}

// Patch applies the patch and returns the patched workerNodeEviction.
func (c *FakeWorkerNodeEvictions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *carbonv1.WorkerNodeEviction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workernodeevictionsResource, c.ns, name, pt, data, subresources...), &carbonv1.WorkerNodeEviction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.WorkerNodeEviction), err
}
