/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	carbonv1 "github.com/alibaba/kube-sharding/pkg/apis/carbon/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeShardGroups implements ShardGroupInterface
type FakeShardGroups struct {
	Fake *FakeCarbonV1
	ns   string
}

var shardgroupsResource = schema.GroupVersionResource{Group: "carbon.taobao.com", Version: "v1", Resource: "shardgroups"}

var shardgroupsKind = schema.GroupVersionKind{Group: "carbon.taobao.com", Version: "v1", Kind: "ShardGroup"}

// Get takes name of the shardGroup, and returns the corresponding shardGroup object, and an error if there is any.
func (c *FakeShardGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *carbonv1.ShardGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(shardgroupsResource, c.ns, name), &carbonv1.ShardGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.ShardGroup), err
}

// List takes label and field selectors, and returns the list of ShardGroups that match those selectors.
func (c *FakeShardGroups) List(ctx context.Context, opts v1.ListOptions) (result *carbonv1.ShardGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(shardgroupsResource, shardgroupsKind, c.ns, opts), &carbonv1.ShardGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &carbonv1.ShardGroupList{ListMeta: obj.(*carbonv1.ShardGroupList).ListMeta}
	for _, item := range obj.(*carbonv1.ShardGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested shardGroups.
func (c *FakeShardGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(shardgroupsResource, c.ns, opts))

}

// Create takes the representation of a shardGroup and creates it.  Returns the server's representation of the shardGroup, and an error, if there is any.
func (c *FakeShardGroups) Create(ctx context.Context, shardGroup *carbonv1.ShardGroup, opts v1.CreateOptions) (result *carbonv1.ShardGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(shardgroupsResource, c.ns, shardGroup), &carbonv1.ShardGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.ShardGroup), err
}

// Update takes the representation of a shardGroup and updates it. Returns the server's representation of the shardGroup, and an error, if there is any.
func (c *FakeShardGroups) Update(ctx context.Context, shardGroup *carbonv1.ShardGroup, opts v1.UpdateOptions) (result *carbonv1.ShardGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(shardgroupsResource, c.ns, shardGroup), &carbonv1.ShardGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.ShardGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeShardGroups) UpdateStatus(ctx context.Context, shardGroup *carbonv1.ShardGroup, opts v1.UpdateOptions) (*carbonv1.ShardGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(shardgroupsResource, "status", c.ns, shardGroup), &carbonv1.ShardGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.ShardGroup), err
}

// Delete takes name of the shardGroup and deletes it. Returns an error if one occurs.
func (c *FakeShardGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(shardgroupsResource, c.ns, name), &carbonv1.ShardGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeShardGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(shardgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &carbonv1.ShardGroupList{})
	return err
}

// Patch applies the patch and returns the patched shardGroup.
func (c *FakeShardGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *carbonv1.ShardGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(shardgroupsResource, c.ns, name, pt, data, subresources...), &carbonv1.ShardGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*carbonv1.ShardGroup), err
}
