// Code generated by MockGen. DO NOT EDIT.
// Source: proxy/apiset/worker_eviction.go

// Package apiset is a generated GoMock package.
package apiset

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/alibaba/kube-sharding/pkg/apis/carbon/v1"
)

// MockWorkerEvictionAPIs is a mock of WorkerEvictionAPIs interface.
type MockWorkerEvictionAPIs struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerEvictionAPIsMockRecorder
}

// MockWorkerEvictionAPIsMockRecorder is the mock recorder for MockWorkerEvictionAPIs.
type MockWorkerEvictionAPIsMockRecorder struct {
	mock *MockWorkerEvictionAPIs
}

// NewMockWorkerEvictionAPIs creates a new mock instance.
func NewMockWorkerEvictionAPIs(ctrl *gomock.Controller) *MockWorkerEvictionAPIs {
	mock := &MockWorkerEvictionAPIs{ctrl: ctrl}
	mock.recorder = &MockWorkerEvictionAPIsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerEvictionAPIs) EXPECT() *MockWorkerEvictionAPIsMockRecorder {
	return m.recorder
}

// SetWorkerNodeEviction mocks base method.
func (m *MockWorkerEvictionAPIs) SetWorkerNodeEviction(eviction *v1.WorkerNodeEviction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkerNodeEviction", eviction)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkerNodeEviction indicates an expected call of SetWorkerNodeEviction.
func (mr *MockWorkerEvictionAPIsMockRecorder) SetWorkerNodeEviction(eviction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkerNodeEviction", reflect.TypeOf((*MockWorkerEvictionAPIs)(nil).SetWorkerNodeEviction), eviction)
}
